apps/blueman-adapters, apps/blueman-applet, apps/blueman-assistant, apps/blueman-browse, apps/blueman-manager, apps/blueman-mechanism, apps/blueman-report, apps/blueman-sendto, apps/blueman-services, module/_blueman.pyx
=> Use /usr/bin/env

blueman/main/Device.py
As reported by @Plaque-fcc in #19
=> Fixes maximum recursion depth exceeded

configure.ac
This should work fine but another set of eyes on it to make sure I am not forgetting something :smile:
=> Check for supported python3 versions at configure

CHANGELOG.md, blueman/Functions.py, blueman/gui/manager/ManagerDeviceMenu.py, blueman/plugins/applet/KillSwitch.py, blueman/plugins/applet/TransferService.py, blueman/plugins/mechanism/RfKill.py
And then perhaps it is time to do 2.1?
=> Proposal to add to 2-0-stable

blueman/gui/GtkAnimation.py
Recently I was looking at the old gtk2 blueman version in Ubuntu 14.04. And unfortunately the move to Gtk3/GI broke most of the fading. I fixed the TreeRow(Color)Fade, which leaves CellFade.
I have a partial fix but it is not perfect as the rows in the treeview have a slight gradient for me. Which means the are small color inconsistencies. I will keep poking at this to make it work properly but do we want to have it merged as it is now, imperfect as it is? Below is the commit message,
```
* Clip only after all rectangles are added to the cairo context
* Use background color as source color.
TODO: Background color is not completely correct but Gtk.render_background
does not work either..
```
=> RFC: GtkAnimation: Fix CellFade fading

blueman/main/NetConf.py
* dhcp handler died and we attempt to kill a non existing process
* a stale lockfile was found but no pid was populated
=> NetConf: Handle a few corner cases

CHANGELOG.md, blueman/main/NetConf.py, blueman/plugins/mechanism/Network.py, blueman/plugins/services/Network.py, data/org.blueman.gschema.xml, data/ui/services-network.ui
This work well for me but would be nice if others can confirm this works for them as well.
=> Udhcpd support

CHANGELOG.md, apps/blueman-adapters, apps/blueman-assistant, apps/blueman-mechanism, blueman/Functions.py, blueman/gui/manager/ManagerMenu.py, blueman/plugins/applet/PowerManager.py, data/ui/assistant.ui
This is a backport of 4fc3a8facbc09e0820bacea28e6a379e3065c975
=> Backport rename of random pass key to 2.0 branch

blueman/main/applet/BluezAgent.py
According to [1] BlueZ should call the Cancel method on the agent but for
some reason it doesn't. See [2]
[1] https://git.kernel.org/cgit/bluetooth/bluez.git/tree/doc/agent-api.txt
[2] https://github.com/blueman-project/blueman/issues/164
=> BluezAgent: Close Notification when pair in successful

blueman/Functions.py
=> Functions: Add function to determine type string from BT Class

blueman/plugins/mechanism/Network.py, blueman/plugins/services/Network.py, data/org.blueman.gschema.xml, data/ui/services-network.ui
This is untested right now but will make sure it does not break anything if ppl agree to remove. The ui widgets do nothing and the code is either missing (NAT) or never called (GN), time to clean them out. Agreed?
=> RFC: Service ui cleanup

blueman/Functions.py, blueman/gui/DeviceList.py, blueman/gui/DeviceSelectorList.py, blueman/gui/manager/ManagerDeviceList.py
=> DeviceList: cleanups round one

blueman/gui/Notification.py
=> Notification: Fix fallback when no daemon is available and no actions

apps/blueman-manager.in, blueman/main/AppletService.py
Also added a couple small changes that I noticed while working on blueman-manager for this port.
=> Port AppletService to GDBus

CHANGELOG.md
Doing a PR so we can have a quick discussion whether it is time to do a first alpha release. So much has changed so it would be good if it got some more exposure.
If not what do you think should be done before that can happen?
=> Update CHANGELOG and time for an alpha?

blueman/main/Mechanism.py, blueman/plugins/applet/DhcpClient.py, blueman/plugins/applet/KillSwitch.py, blueman/plugins/applet/Networking.py, blueman/plugins/applet/PPPSupport.py, blueman/plugins/services/Network.py, blueman/services/meta/SerialService.py
This ports the remaining mechanism proxy to GDBus. 
This leaves us with the remaining client code to be ported the NMPAN, NMDUN and Netusage plugins.
=> Port Mechanism proxy to GDBus

blueman/bluez/PropertiesBase.py, blueman/plugins/applet/DiscvManager.py
=> No cached properties

apps/blueman-mechanism.in
Also added a small commit that ``dprint``'s the exception when the proxy creation failed.
=> blueman-mechanism: Port Polkit client code to GDBus

apps/blueman-manager.in, blueman/gui/Notification.py, blueman/main/applet/BluezAgent.py, blueman/plugins/applet/DhcpClient.py, blueman/plugins/applet/NMDUNSupport.py, blueman/plugins/applet/PPPSupport.py, blueman/plugins/applet/RecentConns.py, blueman/plugins/applet/SerialManager.py, blueman/plugins/applet/StatusIcon.py, blueman/plugins/applet/TransferService.py
This drops the libnotify dep :smile:. Still need lots of testing in the various places, especially actions.
=> Use DBus for sending notifications

blueman/plugins/applet/NMPANSupport.py
This one works now but please test and let me know if there are any issues.
Some improvements in the future which I'll leave for the future.
* The device holds both the active connection and available connections so no need to traverse all connections.
* The device also hold the bluetooth device address in the interface property. We could use this to check against instead of retrieving all properties from the NM bluetooth device.
* The only reason we need the NM bluetooth device is to check whether it is a PAN or a DUN device
=> NMPANSupport: port to gdbus

CHANGELOG.md, apps/blueman-adapters.in, blueman/main/Adapter.py, data/blueman-adapters.desktop.in
=> Make blueman-adapters (Xfce-)pluggable

Makefile.am, configure.ac, sendto/Makefile.am, sendto/caja_blueman_sendto.py
Needs a little cleanup still but is functional. Comments, criticism etc welcome.
Instead of doing a very complicated extension to use the DeviceSelectorWidget just call ``blueman-sendto`` with the appropriate argument for the files. ref #220
=> Simple sendto plugin for caja, nemo and nautilus

blueman/plugins/applet/PPPSupport.py
See https://github.com/blueman-project/blueman/pull/601#issuecomment-255774109
=> Small fixes for PPPSupport plugin

blueman/gui/manager/ManagerDeviceMenu.py, blueman/gui/manager/ManagerMenu.py, blueman/plugins/manager/Info.py, blueman/plugins/manager/Notes.py
=> Manager: add accelerators to manager menus when missing

blueman/plugins/applet/DBusService.py, blueman/plugins/applet/RecentConns.py
untested but this is what I was thinking of to fix #607.
=> Recentconns: Do not use service object

apps/blueman-adapters.in, apps/blueman-applet.in, apps/blueman-assistant.in, apps/blueman-manager.in, apps/blueman-mechanism.in, apps/blueman-rfcomm-watcher.in, apps/blueman-sendto.in, apps/blueman-services.in, blueman/gui/DeviceList.py, configure.ac
=> Allow Adwaita icons

blueman/gui/manager/ManagerDeviceList.py
See https://github.com/blueman-project/blueman/issues/648#issuecomment-277299335
=> ManagerDeviceList: Add fallback for device icon

blueman/bluez/Base.py, blueman/bluez/Manager.py, blueman/bluez/obex/Manager.py
=> Bluez: Do not autostart when constructing the dbus objects

blueman/plugins/manager/Info.py
Some small cleanups included as well. See below for screenshot.
=> Allow users to copy the data from the store

apps/blueman-assistant.in, apps/blueman-sendto.in, blueman/gui/GenericList.py, blueman/plugins/applet/DiscvManager.py, blueman/plugins/applet/RecentConns.py, blueman/plugins/applet/StatusIcon.py, blueman/plugins/services/Network.py
This is a WIP branch to get rid off too broad exception handling. Due to #620 I needed to review exception anyway so took the opertunity to fix them and document the ones not fixed yet. This is not all of them but will update as I go through the code.
edit: All except one sorted out now.
=> Too broad exception handling

blueman/plugins/services/Network.py, data/ui/services-network.ui
=> Some blueman-services fixes

blueman/plugins/applet/KillSwitch.py
**Untested** (tested now, works ok so far) work in progress but this is what I am thinking of to add connmans support.
>Connman blocks the rfkill device for writing and we need to use it to
>set the power state.
=> WIP: KillSwitch: Add support for connman

apps/blueman-assistant.in, apps/blueman-mechanism.in, blueman/Constants.py.in, blueman/Functions.py, blueman/bluez/Base.py, blueman/bluez/Manager.py, blueman/bluez/obex/Client.py, blueman/bluez/obex/Manager.py, blueman/bluez/obex/ObjectPush.py, blueman/bluez/obex/Transfer.py, blueman/gui/Notification.py, blueman/gui/manager/ManagerDeviceMenu.py, blueman/main/Applet.py, blueman/main/Manager.py, blueman/main/NetConf.py, blueman/main/PluginManager.py, blueman/plugins/applet/DhcpClient.py, blueman/plugins/applet/KillSwitch.py, blueman/plugins/applet/NMPANSupport.py, blueman/plugins/applet/PPPSupport.py, blueman/plugins/manager/Services.py, blueman/plugins/services/Network.py, blueman/services/meta/SerialService.py, module/_blueman.pyx.in, module/modem-prober.c
Some more workarounds and compat code that can be dropped now.
=> More python2

blueman/gui/Animation.py, blueman/gui/CommonUi.py, blueman/gui/DeviceList.py, blueman/gui/DeviceSelectorList.py, blueman/gui/DeviceSelectorWidget.py, blueman/gui/GenericList.py, blueman/gui/manager/ManagerDeviceList.py, blueman/gui/manager/ManagerDeviceMenu.py, blueman/gui/manager/ManagerToolbar.py, blueman/main/Services.py, blueman/plugins/applet/ShowConnected.py
This contains one agreed change to show the website url on the about dialog.
=> Small fixes and cleanups

apps/blueman-report.in, blueman/Constants.py.in, blueman/Functions.py, blueman/gui/CommonUi.py, blueman/main/Adapter.py, blueman/main/Applet.py, blueman/main/Manager.py, blueman/main/Sendto.py, blueman/plugins/applet/RecentConns.py
>When using from blueman.Functions/Constants import * we pollute the
>importing module with all the imports done in these two modules.
=>  Limit what is imported from Functions and Constants

apps/blueman-report.in, blueman/Constants.py.in, blueman/Functions.py, blueman/gui/CommonUi.py, blueman/gui/DeviceList.py, blueman/gui/DeviceSelectorList.py, blueman/gui/GenericList.py, blueman/gui/applet/PluginDialog.py, blueman/gui/manager/ManagerDeviceList.py, blueman/main/Adapter.py, blueman/main/Applet.py, blueman/main/Manager.py, blueman/main/Sendto.py, blueman/main/Services.py, blueman/plugins/applet/RecentConns.py
Using dictionaries makes it much easier to add new features. And a nice side effect is that it makes the code much more readable 😨 
At the moment there is no way to add a cairo.Surface to a GtkListStore and I will use a cell data function to retrieve the surface instead.
=> Prepatory work for using cairo surfaces for device icons

blueman/gui/DeviceList.py
=> DeviceList: Use AnyAdapter for receiving signals

apps/blueman-sendto.in, blueman/gui/DeviceList.py, blueman/gui/DeviceSelectorDialog.py, blueman/gui/DeviceSelectorList.py, blueman/gui/DeviceSelectorWidget.py, blueman/main/Sendto.py
The logic has been added just need to make the spinner and combobox look nicer. See #595 for the details on this.
=> Sendto: Replace progresbar with spinner and always discover devices

blueman/gui/applet/PluginDialog.py, data/ui/applet-plugins-widget.ui
This is how it looks like now.
=> Small UI changes in plugindialog

blueman/main/NetConf.py, blueman/plugins/services/Network.py
Backported from master.
Also, can someone verify using isc-dhcpd works on jessie? its broken for me.
=> 2-0-stbale: Fixes the network services ui

blueman/main/NetConf.py
This works nicely for me but would be good to get some more testing.
TODO: If possible we, at some point, should read stdout and log it, read stderr and add it to the errordialog.
=> This adds support for ip command to setup network interfaces

blueman/DeviceClass.py, blueman/bluez/Base.py, blueman/gui/manager/ManagerDeviceList.py
These devices do not expose a Class property and we relied on it to
create the caption in the list.
=> Use Appearance property for bluetooth LE devices

.gitignore, apps/Makefile.am, apps/blueman-tray.in, blueman/gui/Notification.py, blueman/main/Makefile.am, blueman/main/Tray.py, blueman/main/applet/BluezAgent.py, blueman/main/indicators/AppIndicator.py, blueman/main/indicators/GtkStatusIcon.py, blueman/main/indicators/Makefile.am, blueman/plugins/applet/AppIndicator.py, blueman/plugins/applet/AuthAgent.py, blueman/plugins/applet/DBusService.py, blueman/plugins/applet/DhcpClient.py, blueman/plugins/applet/DiscvManager.py, blueman/plugins/applet/ExitItem.py, blueman/plugins/applet/Menu.py, blueman/plugins/applet/NMDUNSupport.py, blueman/plugins/applet/NetUsage.py, blueman/plugins/applet/PPPSupport.py, blueman/plugins/applet/PowerManager.py, blueman/plugins/applet/RecentConns.py, blueman/plugins/applet/SerialManager.py, blueman/plugins/applet/StandardItems.py, blueman/plugins/applet/StatusIcon.py, configure.ac
Making my work on #610 visible. Far from done.
=> Tray application

blueman/plugins/applet/PowerManager.py
=> PowerManager: Update adapter_state on adapter power changes

blueman/Functions.py, blueman/gui/DeviceList.py, blueman/main/Applet.py, blueman/plugins/applet/PowerManager.py, blueman/plugins/applet/RecentConns.py
The code suggest that before an adapter may not be fully ready yet. AFAICS
this is not the case anymore with BlueZ 5 and GDBus.
=> Drop wait_for_adapter for current BlueZ and blueman

blueman/main/Manager.py, blueman/plugins/applet/DBusService.py, blueman/plugins/applet/SerialManager.py, blueman/plugins/mechanism/Rfcomm.py, blueman/services/meta/SerialService.py
Lots of small fixes for issues I found testing the SerialManager.
Turns out that releasing the rfcomm device as normal user failed with permission denied when using the command line utility. So it looks like we are only allowed to release it as root.
=> Fix lots of small issues with rfcomm and serial

.travis.yml, configure.ac, module/Makefile.am
Instead of blueman changing the build system
=> unset PYTHON_CFLAGS to fix build

.travis.yml
It is a bit flaky and slow at times but it does work. Let's see if this PR passes.
=> Make travis use xenial

apps/blueman-assistant
=> spelling issue

.circleci/config.yml
I tested CircleCI and it is a good replacement for travis. It needs the owner to set it up but this config file work well on my fork.
Thanks for mentioning CircleCI :smile_cat: 
edit: forgot to add a link to the build I hope you can see it.
edit 2: link can not be accessed publicly. New public url for the build
https://circleci.com/gh/infirit/blueman/41
=> CircleCI works pretty well!

CHANGELOG.md, blueman/plugins/mechanism/Network.py, blueman/plugins/mechanism/Ppp.py, blueman/plugins/mechanism/RfKill.py, configure.ac, data/configs/org.blueman.Mechanism.conf, data/configs/org.blueman.policy.in
Per e-mail discussion. merge and release? Opinions?
=> Polkitauth 2 0

CHANGELOG.md
The changes are not 100% consistent as they are not linear but I think it is a good idea to have the 2.0 changelog entries in master as well.
=> Merge changelog from 2-0-stable

blueman/gui/manager/ManagerDeviceMenu.py
=> Fix generic connect when ServiceUUID.short_uuid is None

apps/blueman-sendto, blueman/gui/DeviceSelectorDialog.py, blueman/gui/DeviceSelectorWidget.py, blueman/main/Sendto.py
Split from #789 which was getting too large
=> Several cleanups for blueman-sendto

blueman/Functions.py, blueman/gui/DeviceList.py, blueman/gui/manager/ManagerStats.py, blueman/main/PPPConnection.py
Will rebase when #951 is merged.
=> Handle checks in adapter_path_to_name and use raw strings for re

blueman/main/NetConf.py
This does not solve the dhcpd problem reported in #943. But for now, as @cschramm suggested, lets disable dns as we don't need it anyway.
=> Fix some NetConf / dhcphandler issues

blueman/main/NetConf.py
=> NetConf: Fix silly typo in DnsMasqHandler

blueman/main/NetConf.py, blueman/main/PPPConnection.py, blueman/plugins/applet/NetUsage.py, blueman/plugins/applet/PPPSupport.py, blueman/plugins/mechanism/RfKill.py
* Forward port calling list on map object, it return an iterator
* Use with statement, context managers :straight_ruler: 
* Use subprocess.Popen instead of os.popen
* Make a few methods static
=> Use with statement, drop deprecated os.popen and call list on map object

blueman/gui/manager/ManagerDeviceMenu.py, blueman/plugins/applet/DBusService.py, blueman/plugins/mechanism/Ppp.py, blueman/services/DialupNetwork.py, blueman/services/meta/SerialService.py
These commits are partly taken from master and one that needs forward port to master.
=> Fixes for next stable

blueman/DeviceClass.py
This works for the example in #961 and my LE devices that expose appearance. I am not great with bitwise operation so please check that extra :smile:
=> Fix #961 / Handle invalid appearance

CHANGELOG.md, blueman/DeviceClass.py, blueman/gui/manager/ManagerDeviceList.py, blueman/main/Device.py, blueman/main/NetConf.py
I created a buster vm to check out the nftables change and noticed ifconfig was not available by default. It also didn't look nice because of the caption and icons for LE devices.
This cherry-picked the changes and dependant commits from master. The icon change is redone as master diverged too much for cherry-picking.
ps: I promise this is the last PR for 2.7 :grimacing:
=> A few more fixes for 2.0

CHANGELOG.md, Dependencies.md, blueman/main/NetConf.py
I think I added the important bits in the CHANGELOG. Let me k now if you see any I missed or like added.
=> Updates before next alpha

Dependencies.md
=> Add adwaita-icon-theme and Papirus to dependencies

blueman/main/NetConf.py
=> [NetConf] Handle UnpicklingError

blueman/plugins/manager/Info.py
These are of interest for le devices.
=> Info manager plugin: Add new interesting properties

blueman/plugins/applet/NetUsage.py
The org.freedesktop.NetworkManager.Device.Serial interface got dropped in NetworkManager 0.9 and we require NM-1.0.gir and thus NetworkManager 1.0 or later.
=> [NetUsage] Drop PPPStats

blueman/plugins/applet/TransferService.py
=> Handle invalid directory for incoming file transfers

configure.ac
=> Replace invalid checks for icon themes with message

.gitignore, apps/Makefile.am, apps/blueman-adapters.in, apps/blueman-applet.in, apps/blueman-assistant.in, apps/blueman-manager.in, apps/blueman-mechanism.in, apps/blueman-report.in, apps/blueman-rfcomm-watcher.in, apps/blueman-sendto.in, apps/blueman-services.in, apps/blueman-tray.in, configure.ac
=> Set shebang to configured python interpreter

blueman/Functions.py, blueman/main/Manager.py, data/org.blueman.gschema.xml
=> Ask user for auto-power-on setting

blueman/plugins/applet/RecentConns.py
Use a cached property method instead of relying on recover_state getting called at all relevant places to make sure e.g. that the items are initialized when notify gets called.
=> Improve RecentConns state recovery

blueman/main/Adapter.py, blueman/main/Manager.py
If there is another place I missed let me know.
=> Check if an Adapter is present and exit if none found

README.md
=> Add information about the mixed GPL licenses

blueman/Functions.py, blueman/main/DhcpClient.py, blueman/plugins/services/Network.py, module/_blueman.pyx, module/libblueman.c, module/libblueman.h
Includes type annotations so for when 2.1 is released and master is free again.
=> Re-implement retrieval of network interface info

CHANGELOG.md, blueman/plugins/applet/RecentConns.py
=> Fix method call in RecentConns

blueman/gui/DeviceList.py, blueman/gui/manager/ManagerDeviceList.py, blueman/plugins/manager/Info.py
See https://github.com/blueman-project/blueman/issues/1066#issuecomment-508560167
=> Several fixes

Dependencies.md, configure.ac
=> Add minimum version for PyGObject

.circleci/config.yml, blueman/bluez/Base.py, blueman/bluez/__init__.py, blueman/bluez/obex/__init__.py, blueman/main/DBusProxies.py, blueman/plugins/BasePlugin.py, blueman/plugins/applet/RecentConns.py, blueman/plugins/manager/Notes.py, blueman/services/__init__.py, blueman/services/meta/__init__.py
We currently need to use --ignore-missing-imports as we do not have useful gi stubs and cannot use the following switches from --strict without changes:
--disallow-subclassing-any (due to the missing imports)
--disallow-untyped-defs
--check-untyped-defs
=> Add mypy to CircleCI configuration

blueman/bluez/obex/Manager.py, blueman/gui/GtkAnimation.py, blueman/gui/MessageArea.py, blueman/gui/applet/PluginDialog.py, blueman/gui/manager/ManagerDeviceList.py, blueman/gui/manager/ManagerMenu.py, blueman/main/Manager.py, blueman/main/applet/BluezAgent.py, blueman/plugins/applet/NetUsage.py, blueman/plugins/applet/TransferService.py, blueman/services/meta/SerialService.py
ManagerProgressbar is the only class that actually tracks and disconnects signals dynamically.
=> Use disconnect_by_func where possible

blueman/plugins/applet/PowerManager.py
=> Update adapter state on powered property change

blueman/gui/DeviceList.py
Thanks @MikuChan03 for pointing out the problem and the solution.
=> DeviceList: Do not emit adapter-changed twice

blueman/gui/manager/ManagerDeviceList.py, blueman/gui/manager/ManagerDeviceMenu.py
Updated OP as I added a few more commits.
=> A few fixes and refactor for ManagerDeviceMenu

blueman/Makefile.am
https://github.com/blueman-project/blueman/pull/1087#issuecomment-541432245
=> Add typing.py to Makefile.am

blueman/plugins/applet/SerialManager.py
There is a disconnect between typeshed and the std lib annotation.
fixes #1118
TypeError: 'type' object is not subscriptable
=> SerialManager: Quote Popen annotation

.circleci/config.yml
To avoid surprises and PR are blocked. Or make the mypy checks optional for now..
=> Mypy is a fast moving target

blueman/Service.py, blueman/plugins/applet/DBusService.py, blueman/plugins/applet/NMPANSupport.py, blueman/plugins/applet/SerialManager.py, blueman/plugins/manager/Services.py, blueman/services/DialupNetwork.py, blueman/services/Functions.py, blueman/services/GroupNetwork.py, blueman/services/NetworkAccessPoint.py, blueman/services/SerialPort.py, blueman/services/meta/NetworkService.py, blueman/services/meta/SerialService.py
=> Add types to blueman.services

blueman/bluez/__init__.py, blueman/bluez/obex/__init__.py, blueman/gui/DeviceList.py, blueman/gui/manager/ManagerMenu.py, blueman/main/Adapter.py, blueman/main/Applet.py, blueman/main/Manager.py, blueman/main/Sendto.py, blueman/main/applet/BluezAgent.py, blueman/plugins/applet/GameControllerWakelock.py, blueman/plugins/applet/PowerManager.py, blueman/plugins/applet/SerialManager.py, blueman/plugins/applet/TransferService.py, blueman/plugins/manager/PulseAudioProfile.py, blueman/services/Functions.py, blueman/services/meta/NetworkService.py
As an indication how much it was used this reduced code size by 4 lines :eyes: 
I mentioned this also in the commit message, I think it makes sense to move all the bluez classes into a single file. The largest is bluez.Base with ~140, the others are usually no more than 40.
=> Do not import bluez and bluez.obex classes in modules

blueman/main/PluginManager.py
=> PluginManager: Workaround python3.6 typing limitation

.circleci/config.yml, blueman/gui/DeviceList.py, blueman/gui/DeviceSelectorWidget.py, blueman/gui/MessageArea.py, blueman/gui/manager/ManagerDeviceList.py, blueman/gui/manager/ManagerDeviceMenu.py, blueman/main/Adapter.py, blueman/main/DhcpClient.py, blueman/main/Manager.py, blueman/main/NetConf.py, blueman/main/PPPConnection.py, blueman/main/PluginManager.py, blueman/main/Sendto.py, blueman/main/applet/BluezAgent.py, blueman/plugins/AppletPlugin.py, blueman/plugins/applet/KillSwitch.py, blueman/plugins/applet/NetUsage.py, blueman/plugins/applet/RecentConns.py, blueman/plugins/applet/TransferService.py, blueman/plugins/manager/PulseAudioProfile.py
mypy 0.740 improved --check-untyped-defs by giving self the correct type instead of Any and thus requires us to improve some annotations / usages
=> Improve type annotations

blueman/bluez/Adapter.py, blueman/bluez/AgentManager.py, blueman/bluez/AnyBase.py, blueman/bluez/Base.py, blueman/bluez/Device.py, blueman/bluez/Manager.py, blueman/bluez/Network.py, blueman/bluez/NetworkServer.py, blueman/bluez/errors.py, blueman/bluez/obex/AgentManager.py, blueman/bluez/obex/Client.py, blueman/bluez/obex/Manager.py, blueman/bluez/obex/ObjectPush.py, blueman/bluez/obex/Session.py, blueman/bluez/obex/Transfer.py, blueman/plugins/applet/TransferService.py, blueman/services/meta/NetworkService.py
=> Add types to blueman.bluez

blueman/Functions.py
Mentioned by @infirit in #1125 and double checked with [vulture](https://github.com/jendrikseipp/vulture)
=> Drop unused functions in Functions.py

blueman/Makefile.am, blueman/bluez/Manager.py, blueman/bluez/obex/Manager.py, blueman/gobject.py, blueman/main/DBusProxies.py, blueman/main/PulseAudioUtils.py, test/bluez/obex/test_manager.py, test/bluez/test_manager.py, test/main/test_dbus_proxies.py, test/main/test_pulseaudio_utils.py, test/test_gobject.py
We define multiple GObjectMeta-based classes to implement the same argument-independent singleton pattern. This is now combined into a single SingletonGObjectMeta class.
=> Refactor singleton GObjects

CHANGELOG.md, blueman/main/applet/BluezAgent.py
=> Fix pincode entry response

meson.build
The rest appears to still works properly so just the version bump.
=> Update version in meson.build

.circleci/config.yml, blueman/bluez/AnyBase.py, test/bluez/obex/test_imports.py, test/bluez/test_imports.py, test/gui/applet/test_imports.py, test/gui/manager/test_imports.py, test/gui/test_imports.py, test/main/applet/test_imports.py, test/main/indicators/test_imports.py, test/main/test_imports.py, test/module/test_imports.py, test/plugins/applet/test_imports.py, test/plugins/manager/test_imports.py, test/plugins/mechanism/test_imports.py, test/plugins/services/test_imports.py, test/plugins/test_imports.py, test/services/meta/test_imports.py, test/services/test_imports.py, test/test_imports.py
Checking if importing all our modules works (for each python version) is the least testing we can do.
=> Add import tests

blueman/plugins/applet/DhcpClient.py
Proxy timeouts are in milliseconds
=> DhcpClient: increase timeout from 120 second

blueman/plugins/applet/DhcpClient.py
There are several problems, the 120ms timeout is the first commit. I'll keep adding commits as I go for  #1173
=> Dhcp client fixes

.circleci/config.yml
See https://circleci.com/gh/blueman-project/blueman/1938 as an example.
=> Install libpulse0 to circleci deps

.circleci/config.yml, meson.build
This tries to get the embedded python lib and fallback on the normal one. Build is ok again on unstable so switched back.
=> Fix build on python 3.8

blueman/gui/manager/ManagerDeviceList.py, blueman/gui/manager/ManagerDeviceMenu.py, blueman/main/indicators/GtkStatusIcon.py
See #1204
@Xenopathic, assuming you use wayland so could you try this out? Under X it's fine.
=> ManagerDeviceMenu: Create menu at pointer

blueman/plugins/applet/KillSwitch.py
=> Fix IOChannel encoding

po/POTFILES.in
fixes potfile generation
Also working on dropping intltool
=> Add correct apps in POTFLES.in

.circleci/config.yml, CHANGELOG.md, blueman/Functions.py
=> Handle os.remove failing in check_single_instance

test/test_imports.py
This gets reported by flake8 3.8
=> Remove useless f-string

blueman/gui/manager/ManagerDeviceList.py
This fixes multiple issues:
- if two devices are removed within the time the fader animation takes,
_self._faderhandler is overwritten with the faderhandler id of the latter
fader, which leads to non-removal of the first fader handler
- if two devices are removed within the time the fader animation takes,
_self._faderhandler is set to None by the first __on_fader_finished
callback, leading to a crash in the second callback because
disconnect is called as `fader.disconnect(None)`
- If /org/bluez/hci0/dev_XX is removed, and then /org/bluez/hci0 is
removed within the time the fader animation takes, the removal of
/org/bluez/hci0 will lead to a second duplicate device_remove_event for
/org/bluez/hci0/dev_XX, as it's not been removed from the liststore
This is one of the required patches to …
=> Fix device removal handling

CHANGELOG.md, blueman/main/Config.py, blueman/plugins/services/Transfer.py
=> Fixes from 2-1-stable

apps/blueman-sendto.in, blueman/Functions.py, blueman/gui/manager/ManagerDeviceList.py, blueman/gui/manager/ManagerMenu.py, blueman/main/Manager.py, blueman/plugins/applet/StandardItems.py, blueman/plugins/applet/TransferService.py, blueman/plugins/manager/Notes.py
Also added a fix and some cleanup of usage of ``launch()``
=> Do not use LaunchContext when event time is zero

blueman/plugins/applet/KillSwitch.py
As per https://www.kernel.org/doc/html/latest/driver-api/rfkill.html
=> Kill switch strings changed

blueman/plugins/applet/KillSwitch.py
Didn't review the latest build failures in #1283 well enough...
=> Fix line length

.gitignore, blueman/main/Applet.py, blueman/plugins/applet/StatusIcon.py
A couple of things I ran into while testing #1304
=> A few fixes (some from #1304)

apps/blueman-adapters.in, apps/blueman-applet.in, apps/blueman-assistant.in, apps/blueman-manager.in, apps/blueman-sendto.in, apps/blueman-services.in, apps/blueman-tray.in, blueman/Constants.py.in, blueman/Sdp.py
I am confused translations worked at all :confused:. Here is what I see without this commit.
=> Set textdomain in blueman's binscripts

blueman/plugins/applet/RecentConns.py
* Actually convert between stored and runtime items
* Add type hints
* Add a cast to resolve the circular type dependency issue
* Rename some internal methods and members
=> Add and fix type hints in RecentConns

blueman/main/NetworkManager.py
=> Fix fstring string GsmSettings

.github/workflows/stale.yml
=> Fix stale issue message

CHANGELOG.md, blueman/plugins/applet/DiscvManager.py
=> Fix an untranslated string in DiscvManager

CHANGELOG.md, blueman/plugins/manager/Info.py
Also mention @cwendling as he fixed most of the untranslated strings lately.
=> Localize message in Info dialog

blueman/DeviceClass.py, blueman/gui/manager/ManagerDeviceList.py
=> Always localize DeviceClass

CHANGELOG.md, blueman/plugins/applet/ShowConnected.py
See #1278 for discussion. This fixes the problem for me and it is an obvious copy paste error.
=> ShowConnected: Fix tooltip when bluetooth is disabled

.github/workflows/weblate.yml
Make sure the downloaded POT file is that of the master branch.
=> Improve weblate workflow

CHANGELOG.md, blueman/main/Manager.py
=> Add standard window / application closing accelerators

blueman/gui/manager/ManagerMenu.py, blueman/main/Manager.py
The function does not work for GApplications
=> Fix invalid Gtk.main_quit calls in manager

.github/workflows/check.yml, .github/workflows/weblate.yml, po/blueman.pot
I picked up #1390 without the manual po update and with the check job.
=> Restore blueman.pot

blueman/plugins/applet/DisconnectItems.py, blueman/plugins/applet/Makefile.am, po/POTFILES.in, po/blueman.pot
=> Add plugin with disconnect menu items

blueman/plugins/applet/ConnectionNotifier.py, blueman/plugins/applet/Makefile.am, po/POTFILES.in
Closes #1374
Causes some fuss in combination with #1418 and #1414. We should probably find some way to merge those up to three notifications.
=> Add plugin for connection notifications

CHANGELOG.md, blueman/gui/manager/ManagerDeviceMenu.py
I realized that this is easy to achieve. It would also be the same for network services but it gets tricky for serial services.
=> Allow cancelling device connection attempts

blueman/plugins/applet/DisconnectItems.py, po/blueman.pot
=> Handle adapter removal in DisconnectItems plugin

blueman/plugins/applet/KillSwitch.py
We basically blocked all of blueman-applet, fixes #1498
Why reading from /dev/rfkill is problematic with kernel 5.11 is still a mystery.
=> KillSwitch: Do not block when there is nothing to read

CHANGELOG.md, blueman/gui/manager/ManagerDeviceList.py, blueman/gui/manager/ManagerDeviceMenu.py, blueman/plugins/manager/Services.py, po/blueman.pot
There are drivers that do not support connecting while a discovery is still active.
Closes #1398
=> Stop discovery and retry connection on initial EAGAIN

blueman/Makefile.am, configure.ac
=> Fix build configuration

CHANGELOG.md, blueman/plugins/applet/RecentConns.py, po/blueman.pot
=> Restore recent connection items on resume

CHANGELOG.md, blueman/main/applet/BluezAgent.py, po/blueman.pot
=> Fix service authorization notifications

blueman/gui/manager/ManagerDeviceList.py
Broken in 8c8346c8ddce315f3357ecd31469ac96646a1404
=> Fix fader for device removal.

blueman/gui/manager/ManagerDeviceList.py, blueman/gui/manager/ManagerDeviceMenu.py, blueman/main/Manager.py, po/blueman.pot
Needs a better icon, feel free to suggest one :smile:
=> Allow user to block a device

meson.build
@ChenQi1989 try this and then set  `-Dpython.purelibdir`
=> Port meson from deprecated python3

blueman/gui/applet/PluginDialog.py, blueman/main/Services.py
- Center position
- Increase border width from 5/6px to 10px
=> UI: Improve look of Services and Plugins windows

apps/blueman-sendto.in, blueman/Functions.py, blueman/gui/DeviceSelectorDialog.py, blueman/gui/GsmSettings.py, blueman/main/Manager.py, blueman/main/Sendto.py, blueman/main/Services.py, data/ui/note.ui, data/ui/rename-device.ui, po/POTFILES.in
This fixes some of the issues related to l10n.
=> l10n: Fix non-localized strings

blueman/gui/applet/PluginDialog.py
=> PluginDialog: Get the correct treeiter

blueman/gui/applet/PluginDialog.py
=> PluginDialog: Get correct treeiter

blueman/gui/manager/ManagerDeviceList.py
=> Fix position of blocked emblem for scales other than 1

CHANGELOG.md, blueman/main/DNSServerProvider.py, blueman/main/Makefile.am, blueman/main/NetConf.py, blueman/plugins/applet/Networking.py, blueman/plugins/mechanism/Network.py, blueman/plugins/services/Network.py, data/org.blueman.gschema.xml, test/main/test_dns_server_provider.py, test/main/test_netconf.py
* Unify DHCP handler classes
* Drop pickled state file
* Pass data explicitly
* Store configuration in GSettings
* Add some tests :tada: 
* Extract DNS server handling
=> Refactor NetConf

CHANGELOG.md, blueman/main/indicators/StatusNotifierItem.py, configure.ac, data/ui/manager-main.ui, meson.build
I'd like to have the statusbar resizing in stable as well. There isn't much else atm but I do like to take this opportunity to test the distcheck changes.
=> Fixes for 2.3.1

Makefile.am, configure.ac, test/Makefile.am, test/apps/Makefile.am, test/bluez/Makefile.am, test/bluez/obex/Makefile.am, test/gui/Makefile.am, test/gui/applet/Makefile.am, test/gui/manager/Makefile.am, test/main/Makefile.am, test/main/applet/Makefile.am, test/main/indicators/Makefile.am, test/module/Makefile.am, test/plugins/Makefile.am, test/plugins/applet/Makefile.am, test/plugins/manager/Makefile.am, test/plugins/mechanism/Makefile.am, test/plugins/services/Makefile.am, test/services/Makefile.am
=> Extra dist tests

blueman/main/indicators/StatusNotifierItem.py
libdbusmenu gets things wrong when signals arrive too frequently (but still with some gap). The interval is completely random - 10 ms turned out too fast as the issue still shows up (probably the gap between the signals is actually lower in those cases), 1 s sounds a lot too long to delay things (just to make broken receiver happy).
Closes #1791
=> Avoid rapid LayoutUpdated signals

README.md
* Remove explicit cell phone technologies.
* Remove Launchpad reference.
* Use badges for Repology and Weblate
=> Polish readme a little bit

CHANGELOG.md, blueman/main/NetworkManager.py
...not device name.
Fixes #1819
=> Find NM PANU connection by bdaddr

CHANGELOG.md, blueman/plugins/applet/Makefile.am, meson.build
=> Actually ship PulseAudioProfile applet plugin

blueman/main/PulseAudioUtils.py
The typeshed update in 0.981 introduces the _Pointer type and makes pointer a function. Using _Pointer seems like the easiest solution here but note that it is not available in older versions.
=> Update types for mypy 0.981

apps/blueman-sendto.in
=> Fix blueman-sendto

.github/workflows/check.yml, blueman/main/PulseAudioUtils.py
Newer versions do not support Python 3.6 anymore.
=> Pin mypy to 0.971

blueman/bluez/AnyBase.py
Its DBusConnection held references to it but at least for AnyNetwork some plugin unload methods even expect it to get destroyed properly.
The `close` methods seems completely unused - or is it some kind of GLib magic?
=> Make AnyBase garbage-collectable

CHANGELOG.md, blueman/gui/manager/ManagerDeviceMenu.py, meson.build
Do you also want to include the DNS change in fa2306abd5c203af22fa5cd75e8d35583ad5690e?
=> For stable

po/LINGUAS, po/ie.po
I think this should be enough for weblate
=> Add Occidental

module/Makefile.am
The seems to work :crossed_fingers:
=> Don't distribute generated _blueman.c

CHANGELOG.md, blueman/plugins/manager/Notes.py, data/ui/adapters-tab.ui, data/ui/applet-passkey.ui, data/ui/applet-plugins-widget.ui, data/ui/gsm-settings.ui, data/ui/net-usage.ui, data/ui/note.ui, data/ui/rename-device.ui, data/ui/send-dialog.ui, data/ui/services-network.ui, data/ui/services-transfer.ui, meson.build
The bulk of this is just modernizing and updating deprecated properties. We target Gtk 3.24 now.
=> UI maintanance and a few fixes

blueman/gui/applet/PluginDialog.py, blueman/main/Adapter.py, blueman/main/Applet.py, blueman/main/Services.py, blueman/plugins/applet/StandardItems.py
If more are needed let me know.
closes #1523
=> Add accels for closing windows/dialogs

.github/workflows/release.yml, .gitignore, CHANGELOG.md, FAQ, blueman/DeviceClass.py, blueman/Functions.py, blueman/gui/manager/ManagerProgressbar.py, blueman/main/DhcpClient.py, blueman/main/NetworkManager.py, blueman/main/PluginManager.py, blueman/plugins/BasePlugin.py, blueman/plugins/applet/DhcpClient.py, blueman/plugins/applet/NetUsage.py, blueman/plugins/applet/SerialManager.py, blueman/plugins/services/Transfer.py, data/org.blueman.gschema.xml, stubs/gi/repository/GLib.pyi
Found via `codespell -S po -L filetest,keypair`
=> Fix typos and ignore byte-compiled cached files

blueman/main/DBusProxies.py
Also included the 2 commits from #1865
=> Properly activate Manager

.github/workflows/check.yml, blueman/main/NetConf.py, configure.ac, module/meson.build
=> NetConf: Handle empty state files

blueman/main/applet/BluezAgent.py, blueman/plugins/BasePlugin.py
I don't get them locally but they look sane to me. Split off from #2103 so CI runs cleanly.
=> Fix flake warnings in CI

blueman/config/AutoConnectConfig.py, blueman/gui/DeviceList.py, blueman/gui/GenericList.py, blueman/gui/applet/PluginDialog.py, blueman/gui/manager/ManagerDeviceList.py, blueman/gui/manager/ManagerDeviceMenu.py, blueman/plugins/manager/Services.py
The last commit addresses #2101. I understand it's very unlikely to fail but I prefer blueman-manager to not crash to desktop. Many exceptions in the our lists are not fatal but this one is.
edit: flake had some suggestions
=> Bunch of cleanups

blueman/main/Services.py, blueman/plugins/ServicePlugin.py, blueman/plugins/services/Network.py, blueman/plugins/services/Transfer.py, data/ui/services-network.ui, data/ui/services-transfer.ui, data/ui/services-window.ui
We really don't need a custom list for this. Also opens up binding settings to widgets.
edit: updated screenshots
=> blueman-services: Make it a notebook

blueman/gui/manager/ManagerDeviceMenu.py, blueman/plugins/applet/StatusIcon.py
We already use them in other places so let's use them everywhere.
=> Use operator convenience functions

blueman/main/PulseAudioUtils.py
Basically use enums for all the magic numbers.
=> Couple of changes for Pulseutils

Dependencies.md
=> notification: Replace gnome spec page for fdo

.github/ISSUE_TEMPLATE.md
I just realized why so many insufficient issues tend to contain hidden text. (Not that making it visible makes them much better... :sweat_smile:)
=> Fix comment in ISSUE_TEMPLATE

blueman/gui/DeviceSelectorDialog.py, blueman/gui/manager/ManagerMenu.py, blueman/gui/manager/ManagerToolbar.py
The device argument is actually optional.
=> Fix device-selected handlers

blueman/gui/manager/ManagerDeviceList.py
=> Copy address to clipboard from manager device list

blueman/gui/manager/ManagerMenu.py, blueman/main/Manager.py, data/ui/manager-main.ui
Here is what I have so far. Still need to:
* cleanup
* drop menu entry
* perhaps change color of the button
The idea here is that the toggle button is "active" when bluetooth is enabled and showing label and icon what would happen if the button is pressed, disable bluetooth.
=> Manager: Use Gtk.Switch to toggle bluetooth status

CHANGELOG.md
Let me know if I missed something / want changes.
=> Update changelog for 2.4

blueman/plugins/applet/PowerManager.py
=> PowerManager: Add back the BluetoothStatusChanged signal

blueman/plugins/applet/ShowConnected.py
#1911 introduced a bug.
Closes #2321
=> Change icon when devices disconnected

blueman/plugins/applet/PulseAudioProfile.py
=> Escape audio profile names for markup

blueman/gui/manager/ManagerDeviceList.py, blueman/plugins/applet/ConnectionNotifier.py, blueman/plugins/applet/PowerManager.py, blueman/plugins/applet/PulseAudioProfile.py, blueman/plugins/applet/ShowConnected.py
I'll gather them in this draft
=> Fixes from stable

data/ui/manager-main.ui
It was somehow dropped in #1776.
=> Add back title to manager window

blueman/main/DBusProxies.py, blueman/plugins/applet/StandardItems.py, data/org.blueman.gschema.xml
=> Add an option to toggle manager visibility on clicking the tray icon

configure.ac, test/Makefile.am, test/services/meta/Makefile.am, test/testhelpers/Makefile.am
This should be the remaining bits for all the tests. Anything else that got missed?
=> Also extradist testhelpers

configure.ac, data/icons/hicolor/48x48/status/Makefile.am, test/Makefile.am, test/services/meta/Makefile.am, test/testhelpers/Makefile.am
#2371 broke the distributed tests.
=> Pick dist fixes from main

po/LINGUAS, po/eo.po, po/ga.po
=> Add Galic and Esperanto translations

.github/workflows/check.yml
3.13 is stable, 3.14 alphas are available
=> Update Python matrix

CHANGELOG.md, blueman/main/PluginManager.py
=> Fix fatal LoadException

blueman/main/indicators/StatusNotifierItem.py
=> StatusNotifierItem: announce children-display

blueman/main/indicators/StatusNotifierItem.py, test/main/Makefile.am, test/main/test_gdbus_error.py
=> Fix GDBus.Error check
