README.md, blueman/bluez/obex/Session.py
Looks like the method wraps the response arguments in a single struct other than org.bluez.obex.ObjectPush1.SendFile.
Closes #129
Closes #196
=> Correctly handle org.bluez.obex.ObjectPush.SendFile replies

CHANGELOG.md, apps/blueman-applet, blueman/gui/Notification.py, data/org.blueman.gschema.xml
~~Using --disable-notification-daemon~~ the user can now choose not to use a notification-daemon at all. Previously the fallback GTK+ notifications were only used if we had to show actions, but the daemon did not report to support them.
Additional changes:
* Fix error message when libnotify cannot be initialized (it is no longer pynotify)
* ~~Fix blueman.Constants.POLKIT (was always false since 1954e2d3ffbc79a0cf696c7fe12bca431d34d368)~~
* Fix issue from GTK+ 3 transition in NotificationDialog (window vs. get_window())
Closes #245
Closes #246
=> Add configuration option to force notification fallback

blueman/main/PulseAudioUtils.py, blueman/plugins/manager/PulseAudioProfile.py
I saw this was broken under python3 and made it work on par with current master. Except for the signal bars not showing under python3. But.... the ui has some problems in master __and__ my python3 branch with __both__ python versions.
What I see is that the menus get confused in that the ```active_profile``` in the menus do not correspond to the actual profile selected. The device menu works better than the right click one.
Work in progress still but my eyes can not handle more for today.
=> PulseAudio python3 support

CHANGELOG.md, configure.ac
The PR to start a quick discussion :smile:.
There is nothing in libblueman or _blueman.pyx that requires the above mentioned libs at build time and should only be available at runtime. And the runtime deps are the introspection (gir/typelib) files not the -dev packages with the pkg-config and header files.
We could print a nice warning at the end of configure to alert the maintainer to make sure the introspection files are added as build deps. Or something else?
=> Gtk, GLib, Gio and Gthread are runtime only deps.

apps/blueman-adapters, apps/blueman-applet, apps/blueman-assistant, apps/blueman-browse, apps/blueman-manager, apps/blueman-mechanism, apps/blueman-rfcomm-watcher, apps/blueman-sendto, apps/blueman-services, blueman/Functions.py
I was getting sick of trying to figure out which python process was blueman-manager, applet etc etc.
It makes use of the c module setproctitle but one could also use ctypes and call into libc directly. Although it uses a 3rd party module it made more sense to me than reinventing the wheel with libc+ctypes.
Opinions?
=> Set a process title for the blueman apps

CHANGELOG.md, blueman/gui/manager/ManagerMenu.py, blueman/plugins/applet/DBusService.py
Allows to open plugins dialog without using the applet.
Closes #264
Closes #282
=> Add plugins button to View menu

blueman/services/Input.py, data/ui/device-list-widget.ui
This makes Blueman compatible with the Adwaita icon theme, which is the default theme in GTK+ 3.
=> Fix non-standard icon names

blueman/gui/CommonUi.py
I changed the sentence from "Blueman is a GTK based Bluetooth manager" to "Blueman is a GTK+ Bluetooth manager", which makes more sense and is frequently used in Blueman documentation.
=> Fix spelling of GTK+

apps/blueman-adapters, apps/blueman-manager, blueman/gui/DeviceSelectorWidget.py, blueman/gui/GsmSettings.py, blueman/gui/applet/PluginDialog.py, blueman/gui/manager/ManagerProgressbar.py, blueman/gui/manager/ManagerStats.py, blueman/plugins/services/Network.py, data/ui/adapters-tab.ui, data/ui/applet-passkey.ui, data/ui/applet-plugins-widget.ui, data/ui/device-list-widget.ui, data/ui/gsm-settings.ui, data/ui/manager-main.ui, data/ui/net-usage.ui, data/ui/send-dialog.ui, data/ui/services-network.ui, data/ui/services-transfer.ui
With [GtkGrid](https://developer.gnome.org/gtk3/stable/GtkGrid.html#GtkGrid.description) we can better layout were widgets and boxes need to go. It replaces the deprecated GtkTable widgets and reduces the number of GtkV/HBoxes.
As this is a fairly invasive change I would like to get a few people test this out. before pushing it.
=> Move to GtkGrid

apps/blueman-adapters, apps/blueman-manager, apps/blueman-sendto, apps/blueman-services, blueman/Functions.py, configure.ac, data/configs/Makefile.am
AFAICS there is nothing in blueman that needs to update the GdkVisual (Gtk3's colormap replacement).
commit message:
```
If we need to handle compositing changes we can connect to the
composited-changed signal on GtkWidget and update with the new
GdkVisual.
```
=> Remove enable_rgba_colormap which does nothing

apps/blueman-adapters, blueman/bluez/PropertiesBase.py
While working on ``blueman-adapters`` I found it strange that we were storing the adapter properties in a separate dict instead of retrieving them when needed. The first commits allows ``PropertiesBase`` to be used as a dictionary. The second commit implements the new functionality in ``blueman-adapters`` getting rid of all the duplicate storage of the properties.
We can also rename the ``get_properties`` to ``items`` which matches the python dictionary terminology better. Which requires changes across all of blueman so I left this out for now.
The new dict like functionality of-course applies to all classes that derive from ``PropertiesBase``.
=> Add dict like functionality to PropertiesBase

data/configs/Makefile.am
Right now unit files are installed in `/user` which is not a very good idea ;-P.
=> build: Fix typo in systemd path variable

apps/blueman-assistant
Oops.
Signed-off-by: Robby Workman <rworkman@slackware.com>
=> Fix missed r_randp -> r_pair in 61a9657452332e278f907d4a2f7149

blueman/main/PPPConnection.py, module/libblueman.c, module/modem-prober.c
\__GLIBC\__ is defined if not defined in order to make the kernel headers work with userspace headers better. musl does not define \__GLIBC\__.
Other distributions usually work around the kernel headers issue by patching kernel headers.
In addition, XCASE must be defined since it is normally provided by glibc's termios.h.
=> Fix building on musl libc

blueman/bluez/PropertiesBase.py
>_on_property_changed does nothing but emit a signal which we can just
as well do from _on_properties_changed.
So the only reason I can think of to have two functions is the name printed on the console. Other than that I find it pretty useless, any objection to merge the two?
=> PropertiesBase: Merge the two property changed functions

blueman/plugins/applet/Networking.py
When a new adapter was added we uncritically register Networking for
all adapters even if we already registered it before.
=> Networking: Do not register already registered adapters

blueman/main/applet/BluezAgent.py
It is unused and without it things get a whole lot less complicated.
=> BluezAgent: Drop the unused signal "released"

apps/blueman-applet, blueman/plugins/AppletPlugin.py, blueman/plugins/applet/GameControllerWakelock.py, blueman/plugins/applet/PowerManager.py, blueman/plugins/applet/RecentConns.py, blueman/plugins/applet/SerialManager.py, blueman/plugins/applet/ShowConnected.py
Applet plugin no longer need to connect their own signals for Adapter and Devices. This is how the plugin system was for the adapter already, we now extend this to the devices too.
See  #440 
There is also a couple of small cleanups in here (first two).
=> Extend the function we have the PluginManager run

apps/blueman-manager, blueman/bluez/Adapter.py, blueman/bluez/AgentManager.py, blueman/bluez/Base.py, blueman/bluez/Device.py, blueman/bluez/Manager.py, blueman/bluez/Network.py, blueman/bluez/NetworkServer.py, blueman/bluez/PropertiesBase.py, blueman/bluez/errors.py, blueman/bluez/obex/AgentManager.py, blueman/bluez/obex/Client.py, blueman/bluez/obex/ObjectPush.py, blueman/bluez/obex/Session.py, blueman/bluez/obex/Transfer.py
This picks a commit that changes the handling of bluez methods from the gdbus migration. It is useful as it allows for more things to be pushed down into ``blueman.bluez.Base`` and simplify things.
Just like in my gdbus branch we now check if we either have an error or reply handler and make the call asynchronous.
Then we show a notification when we fail to pair in blueman-manager. Please let me know if we need to specify what error we got in the notification.
This fixes #453
=> blueman-manager: Fix authentication failed handling

blueman/bluez/Adapter.py, blueman/bluez/AgentManager.py, blueman/bluez/Base.py, blueman/bluez/Device.py, blueman/bluez/Manager.py, blueman/bluez/Network.py, blueman/bluez/NetworkServer.py, blueman/bluez/PropertiesBase.py, blueman/bluez/obex/AgentManager.py, blueman/bluez/obex/Client.py, blueman/bluez/obex/Manager.py, blueman/bluez/obex/ObjectPush.py, blueman/bluez/obex/Session.py, blueman/bluez/obex/Transfer.py
So this does not work as we do not have the necessary info to properly keep track of the objects.
The main problem is that we do not have the ``interface_name`` in ``*args`` or ``**kwargs`` provided to ``__new__`` because we do not create the object with it and provide it as default (keywword)argument. We could force all instances to use keywords and provide the both interface_name and object_path like, ``bluez.Device(interface_name='org.bluez.Device1', obj_path='/org/bluez/...')``.
Another way is to have some sort of BluezObject store/manager that is the only one creating and distributing the objects.
=> Bluez: Implement singleton for bluemans bluez objects

blueman/plugins/applet/SerialManager.py
This requires at least one more fix to fix the below. I don't understand this last one so any hints would be helpful :smile:.
```
on_device_disconnect (/usr/lib64/python3.4/site-packages/blueman/plugins/applet/SerialManager.py:132)
Disconnecting /dev/rfcomm14 
ERROR:dbus.connection:Unable to set arguments ('/dev/rfcomm14',) according to signature 'd': <class 'TypeError'>: a float is required
```
=> Bug fixes for the script handling in SerialManager plugin

.gitignore, apps/Makefile.am, apps/blueman-adapters.in, apps/blueman-applet.in, apps/blueman-assistant.in, apps/blueman-manager.in, apps/blueman-mechanism.in, apps/blueman-report.in, apps/blueman-rfcomm-watcher.in, apps/blueman-sendto.in, apps/blueman-services.in, configure.ac, module/_blueman.pyx.in
This allows building for systems with both Python 2 and 3 without replacing the shebang. Replacing will only be necessary if env shall not be used e.g. as PyEnv might be present (see #435) or a specific minor version needs to be defined (i.e. there are multiple minor versions on the target system and blueman is not built for the newest one; we cannot use minor versions as they are not mandatory, see PEP 394).
This is a solution for #482 (build for AOSC OS without shebang replacement), however it only makes sense for very few distributions that neither have pyenv and nor multiple Python minor versions. More major distributions have some shebang replacement mechanism anyway.
=> Put Python major version in shebang

blueman/gui/manager/ManagerDeviceList.py, blueman/gui/manager/ManagerDeviceMenu.py, blueman/gui/manager/ManagerToolbar.py, blueman/services/Functions.py
This relates to issue comnment https://github.com/blueman-project/blueman/issues/460#issuecomment-184472046.
This does not solve all the errors we get trying to get properties from a removed device though and we need to do the same thing for the audio service. We could also store all the uuids and work of them instead of reading them over and over.
This is a proof of concept to store values in the GtkTreeStore for use in the UI.
Opinions, objection or suggestions (especially on my naming skills :smile:).
=> RFC: Store if device has object push capability in GtkListStore

blueman/Functions.py
As mentioned in #443 we previously never checked if the activation (`SetBluetoothStatus(True)`) is actually successful or if it is still disabled afterward. This is expected if a hardware killswitch is switched off.
=> Check if bluetooth activation is successful

apps/blueman-manager.in, blueman/gui/DeviceSelectorWidget.py, blueman/gui/applet/PluginDialog.py
With many (all?) themes this overlaps the content of the ScrolledWindow, horrible.
=> Disable Gtk overlay scrolling

data/configs/blueman-mechanism.service.in
systemd must not kill processes started by blueman-mechanism, i.e. DHCP handlers.
Fixes #510
=> Fix KillMode for blueman-mechanism.service

apps/blueman-manager.in, blueman/gui/DeviceList.py, blueman/gui/manager/ManagerDeviceList.py, blueman/gui/manager/ManagerMenu.py, data/org.blueman.gschema.xml
Ok, this is WIP but it works. Opening a PR so people can comment, criticize and suggest things.
This makes use of the sorting capabilities of the ListStore so we do not rebuild the list every-time. I will also change how the list behaves when multiple adapters are available. As with the sorting, we should not be rebuilding the list but instead put all devices in the list and use a [filter function](http://python-gtk-3-tutorial.readthedocs.org/en/latest/treeview.html#filtering) to modify the view.
The only "drawback" currently is that it does not animate the row as it does not rebuild, it still animates on new/removed device though. However we gain the ability to apply any sorting algoritm we like on any field in the list.
The old sort menu items are still there but here is a screenshot of …
=> Use the ListStore to sort instead of rebuilding

blueman/plugins/mechanism/Network.py, blueman/plugins/mechanism/Ppp.py, blueman/plugins/mechanism/RfKill.py, data/configs/org.blueman.Mechanism.conf, data/configs/org.blueman.policy.in
@posophe this is for #423
For all, I don't have a machine with a hardware killswitch (only have usb dongles) so I really would appreciate if people can make sure this works properly.
To not have your users to authenticate all the time distros typically ship with a polkit rules file. See below for an example.
```
/* Allow users in wheel group to run blueman network config without authentication */
polkit.addRule(function(action, subject) {
if ((action.id == "org.blueman.network.setup" ||
action.id == "org.blueman.dhcp.client" ||
action.id == "org.blueman.rfkill.setstate" ||
action.id == "org.blueman.pppd.pppconnect") &&
subject.isInGroup("wheel")) {
return polkit.Result.YES;
}
});
```
=> Mechanism: dbus polkit authorisation checking

blueman/main/NetConf.py
This is unfortunate but most people will not even notice we created a new
state file.
We really should just use a plain text format like json or simple ini file. There are only a couple of variables we need to store, ip address, pid and DhcpHandler the rest, afaik, are constructed on the fly.
=> NetConf: Treat UnicodeDecodeError as if there was no file

blueman/plugins/applet/NMDUNSupport.py, blueman/plugins/applet/NMPANSupport.py
So one question, we now rely completely on bluez/networkmanager to handle the connection. This is all ok except the user may remove the connection themselves and we cannot activate the connection. The  question then is, should we still create the connection? I am leaning towards we still create the connection even if it is missing.
This works for me with a PAN phone but I don't have a phone that supports DUN. Would be nice if someone can test this with DUN :smile:
=> Drop old NetworkManager and ModemManager 0.x legacy code

blueman/plugins/applet/DiscvManager.py
So we apparently call on_adapter_removed more than once and it only blows up here. The best solution is to figure out why this is but I do not have the time right now.
```python
on_adapter_removed (/usr/lib64/python3.5/site-packages/blueman/plugins/applet/DiscvManager.py:81)
/org/bluez/hci0 
_________
on_adapter_removed (/usr/lib64/python3.5/site-packages/blueman/plugins/applet/DiscvManager.py:81)
None 
_________
Run (/usr/lib64/python3.5/site-packages/blueman/main/PluginManager.py:208)
Function on_adapter_removed on DiscvManager Failed 
File "/usr/lib64/python3.5/site-packages/blueman/main/PluginManager.py", line 212, in Run
ret = getattr(inst, function)(*args, **kwargs)
File "/usr/lib64/python3.5/site-packages/blueman/plugins/applet/DiscvManager.py", …
```
=> RFC: DiscvManager: Check if adapter is None so we do not error

blueman/plugins/AppletPlugin.py, blueman/plugins/BasePlugin.py
The plugin system is nice but the design is not really documented anywhere. I started documenting by adding docstring to the virtual functions and a few others within the plugin context.
The basic design how I see it is:
- Any setup/tear-down necessary for the plugin to work should be done in on_load and on_unload. This excludes any interaction directly with bluez like manipulating properties, this should be setup in on_manager_state_changed
- on_manager_state_changed indicates whether bluez dbus api is available or not. We should add/remove watches, (dis)connect bluez object signals and setup/clean-up anything bluez related.
- Then we have several the default functions that are run on the plugins which should be used to update state, change the ui etc.
ps: also two commits removing …
=> RFC: Add some comments explaining what the plugin methods should do and do

apps/blueman-applet.in, blueman/bluez/Agent.py, blueman/main/applet/BluezAgent.py, blueman/plugins/AppletPlugin.py, blueman/plugins/applet/AuthAgent.py, blueman/plugins/applet/Networking.py
* GDBus does not error if we create a proxy when bluez is not running.
* If bluez is not running we are unlikely to see signals
* We now only run "on_manager_state_changed" when the name (dis)appears.
------
This does expose a logic bug in BluezAgent resulting in failing to unregister. How are we supposed to unregister when the bluez was stopped? There are also some other smallish changes needed so this is not meant to be merged just yet. I need to go now and revisit this later.
```
__del__ (/usr/lib64/python3.5/site-packages/blueman/main/applet/BluezAgent.py:37)
Exception ignored in: <bound method BluezAgent.__del__ of <blueman.main.applet.BluezAgent.BluezAgent object at 0x7f23c9963588>>
File "/usr/lib64/python3.5/site-packages/blueman/main/applet/BluezA …
```
=> RFC: blueman-applet: Do not create and tear down manager objects

apps/blueman-manager.in, blueman/Functions.py, blueman/gui/MessageArea.py, blueman/gui/manager/ManagerDeviceMenu.py
>We now split and always get the last item as this holds the error message.
>Also call strip() on the string as it may contain a new line and the
>MessageArea will show a "More" button.
>
>This got broken with the GDBus migration of various parts in blueman as
>GLib's exceptions do not match dbus-glib's.
------
There is, imo, a weird implicit behaviour in the ``MessageArea`` where a string containing a newline will trigger the ``More`` button to show up, see [1]. The newline is added by the ``e_`` function when it got an instance of ``Exception``. I would really like to drop this and explicitly send a tuple instead.
Any objections to this? If not I'll add it to this PR.
[1] https://github.com/blueman-project/blueman/blob/master/blueman/gui/MessageArea.py#L168
=> Functions: Fix error formatter function e_()

apps/blueman-adapters.in, blueman/bluez/Adapter.py, blueman/bluez/Manager.py, blueman/bluez/obex/Manager.py, blueman/gui/DeviceList.py, blueman/gui/DeviceSelectorWidget.py, blueman/gui/manager/ManagerMenu.py, blueman/plugins/applet/NetUsage.py, blueman/plugins/applet/Networking.py, blueman/plugins/applet/PowerManager.py, blueman/plugins/applet/RecentConns.py, blueman/plugins/applet/ShowConnected.py, blueman/plugins/applet/StatusIcon.py
This changes a couple of things to make more sense.
* Rename list_* functions to get_* as we are returning proper Adapter and Device objects.
* Move device object handling to the manager, this is the job of the object manager not the adapter.
To then make it possible to subclass from ``Gio.DBusObjectManagerClient``. Tested this quickly and things appear to work well but feedback and more testing appreciated :smile: .
=> Bluez object manager

blueman/bluez/Base.py
The invalidated properties in do_g_properties_changed seems to be broken.
=> Bluez Base: WOrkaround python3 UnicodeDecodeError

apps/blueman-adapters.in, apps/blueman-applet.in, apps/blueman-assistant.in, apps/blueman-manager.in, apps/blueman-mechanism.in, apps/blueman-sendto.in, apps/blueman-services.in
With this it is possible to use the compiled schema from the source tree instead of the one installed in ``/usr/share/glib-2.0/schemas``. One less thing to install 😄 
At some point though we should probably add a new install target that only installs the bits we can not do without like the dbus services.
=> Makes it possible to use the gschema from the source tree

blueman/plugins/manager/Info.py
I have LE devices being picked up by my machine, that are not mine, which do not expose the device class. BlueZ then sends us a zero.
The question is, should we skip it or should we just show zero? This PR does the latter.
I also reworked the properties a bit and added it to the PR.
=> Small rework and bug fix

blueman/bluez/Base.py
Be a little less verbose and not spam logs so much which improves
readability.
=> bluez.Base: print all changed properties in one go

apps/blueman-adapters.in, apps/blueman-rfcomm-watcher.in, apps/blueman-sendto.in
We do not handle when a non existing device is used with bluemna-sendto. ``Manager.find_device`` returns None and when it does exit.
=> Argparse fixes and fix a bug in blueman-sendto

apps/blueman-adapters.in, apps/blueman-applet.in, apps/blueman-assistant.in, apps/blueman-manager.in, apps/blueman-mechanism.in, apps/blueman-sendto.in, apps/blueman-services.in, blueman/Constants.py.in
The apps and data paths currently depend on the working directory (assuming it is `apps`).
A couple of other issues related to BLUEMAN_SOURCE:
I don't get the addition of PYTHONPATH in 508492623b95fb3757498422b19b723e3d8f3b6c. First, the underlying idea is already achieved by modifying `sys.path` and second the correct path, assuming you're in `apps`, should be `..`, not `../blueman`.
508492623b95fb3757498422b19b723e3d8f3b6c also made necessary moves in the code so that the imports happen *after* setting up the path, but #631 reverted that (merged incorrectly?).
Using apps as `BIN_DIR` never worked out of the box as the generated files are not executable. Not sure how and if we could fix that.
=> Make handling of BLUEMAN_SOURCE working directory independent

.gitignore, CHANGELOG.md, apps/blueman-rfcomm-watcher.in, blueman/Constants.py.in, blueman/Functions.py, blueman/main/PPPConnection.py, blueman/plugins/mechanism/Rfcomm.py, blueman/services/meta/SerialService.py, configure.ac
...if he has read and write access.
This requires the watcher to wait if the device is busy which means it's opened by root (or any other user) and typically happens if ModemManager is present and probes the new device. The same method is used for PPPSupport now which previously always waited for five seconds unconditionally. While that is unnessary if ModemManager is not present, it seems to be too short if it is.
Fixes #524.
I'm not 100 % sure about the 0.1 sec delay before checking the access permissions, but if I do it immediately after creating the device, R_OK and W_OK result in False (while E_OK works, so it's not that the file would be absent).
=> [Serial] Open rfcomm device as unprivileged user

CHANGELOG.md, blueman/Sdp.py, blueman/Service.py, blueman/gui/manager/ManagerDeviceList.py, blueman/gui/manager/ManagerDeviceMenu.py, blueman/main/applet/BluezAgent.py, blueman/plugins/applet/NMDUNSupport.py, blueman/plugins/applet/PPPSupport.py, blueman/plugins/applet/RecentConns.py, blueman/plugins/applet/SerialManager.py, blueman/plugins/manager/Info.py, blueman/services/Functions.py
This is @infirit's idea from #648 to fix an inaccuracy in our service class handling where we just took the last 16 bits of the time_low field as a 16-bit short UUID without checking the full UUID is actually a reserved one. The consequence was that we did not differentiate between unknown reserved service classes and prorietary ones and especially that we could possibly confuse proprietary ones with known reserved ones.
=> Implement a ServiceUUID class

blueman/gui/Notification.py, blueman/main/applet/BluezAgent.py
The elements in `_NotificationBubble._callbacks` are invoked with a single argument (the action name), but `_NotificationDialog.callback` was invoked with two arguments: the `_NotificationDialog` instance, and the action name.
Some places expected their callbacks to be invoked one way, some the other.
I've normalised everything to always expect a single argument.
=> invoke _NotificationDialog.callback with 1 argument

blueman/Sdp.py
RecentConns uses the name in the submenu and notifications and currently shows "Proprietary".
=> Fix name for auto connect profiles

blueman/gui/manager/ManagerDeviceList.py
If we fail to get connection info, which is the case currently with LE
devices, we never update the row connected item. Our ManagerDeviceMenu
is not able to correctly show a Disconnect menu item.
=> ManagerDeviceMenu: Always update row with Connected property

blueman/main/DbusService.py
As DbusService's self.locations returns an iterator, signal emission in instance works only once and no more locations to send to are found after that.
=> Fix DBus signal emission

apps/blueman-assistant.in
There is no header any more in Gtk3 however we can replicate one as part of the page. It will require a little work to convert boxes to grids but not too major.
This commit drops the now completely useless setting of images to the header.
=> Discussion: Have a header in the assistant?

configure.ac
Fix missing '$' for variable references in the icon check which caused
it to always fail (-> not detect the issue).
=> configure: Fix typo in icon check

blueman/plugins/applet/RecentConns.py, data/org.blueman.gschema.xml
I wanted to do this for some time. It could use some more work but that is for another time.
Instead of storing a binary blob as string we now store
```
[{'adapter': '00:02:72:C5:BB:B4', 'address': '00:07:61:48:7A:2C', 'alias': 'Logitech MX1000 mouse', 'icon': 'input-mouse', 'name': 'Auto connect profiles', 'uuid': '00000000-0000-0000-0000-000000000000', 'time': '1502298305.8234344', 'device': '', 'mitem': ''},
{'adapter': '00:02:72:C5:BB:B4', 'address': 'D2:0C:FD:5A:21:12', 'alias': 'M720 Triathlon', 'icon': 'input-mouse', 'name': 'Auto connect profiles', 'uuid': '00000000-0000-0000-0000-000000000000', 'time': '1502298328.266433', 'device': '', 'mitem': ''}]
```
=> Store an array of dicts for recent-connections

blueman/Functions.py, blueman/plugins/applet/DiscvManager.py, blueman/plugins/applet/PowerManager.py, blueman/plugins/applet/RecentConns.py
Although it is deprecated it has not been removed till Gtk+4. When we
move to Gtk+4 we can either:
* create our own menuitem through a subclass
* use the ugly menuitems like we did before
* drop icons from menus
I personally lean towards creating our own widget
=> Reintroduce ImageMenuItem

blueman/Functions.py, blueman/gui/Animation.py, blueman/gui/CommonUi.py, blueman/gui/DeviceSelectorList.py, blueman/gui/GenericList.py, blueman/gui/Notification.py, blueman/gui/manager/ManagerDeviceList.py, blueman/gui/manager/ManagerMenu.py, blueman/gui/manager/ManagerStats.py, blueman/main/Manager.py, blueman/main/Services.py, blueman/plugins/ManagerPlugin.py, blueman/plugins/manager/Services.py
Posting for interested people. The goal here is to prepare to use cairo surfaces to paint the trusted and paired icons over the device icon. Then when the cairo surface device scaling functions are in a released version of pycairo we can have nice crisp device icons when scaling. The GdkCellRenderePixbuf has a surface property so when I figure out how to use that we can drop all pixbufs.
I'll probably push some commits like the clean-ups of fake device and unused import in the next week.
ps: I have a silly example that uses a patched pycairo that shows how this is done.
https://gist.github.com/infirit/22b147bcdcdc1ed4584f1f513fd1855e
=> (Manager)DeviceList scaling work

blueman/gui/manager/ManagerDeviceList.py
>For example, if rssi was exactly 30 rssi_state wouldn't be set. Revised
after correction by @cshramm
This should cover everything (I hope 😨)
=> ManagerDeviceList: Fix logic to determine rss and tpl state

blueman/plugins/manager/Services.py, blueman/services/meta/NetworkService.py, blueman/services/meta/SerialService.py
For NetworkService we now handle the missing dbus interface gracefully.
For SerialService the devices I have either don't expose the uuid until
paired or ask to be paired when we attempt to connect.
Also set menu entry sensitive based of this.
=> Network and Serial Service: Add property for availability

blueman/main/PPPConnection.py
PyCharm flagged this but I have no devices that use PPP. Needs a tester but it has been broken for some time now so not sure how many folks still use this..
=> Send bytes to os.write

blueman/gui/manager/ManagerDeviceList.py
It actually updates the TreeView on window move, mouse over and when we set values. It is just too noisy even with the changes in this PR.
* Drop logging in get_icon_info
* Reduce number of times we update the list store
* Drop pointless ``if True``.
=> Level setup changes

apps/blueman-mechanism.in
This is useful for debugging so we can keep it running in a terminal.
=> mechanism: Add option to stop timer

blueman/main/NetConf.py
This works properly on gentoo and debian jessie. Will backport to 2.0 when merged and add it to #736
=> Fix dhcpd pid handling

blueman/gui/Notification.py
>We should probably use AppIndicator for status icon but I rather not
>do big changes in 2.0. So workaround it by returning zero when we get
>weird x and y values from get_geometry.
This fixes #762. I decided for a slightly different solution than what was posted in #762.
=> Notification: Make sure x and y hint are in screen geometry

blueman/plugins/applet/AppIndicator.py, blueman/plugins/applet/StatusIcon.py
I have been experimenting with AppIndicator and noticed we never set its title. The title, afaics, is AppIndicator terminology for setting the tooltip.
While working on this I also found that the number of connections went missing on the title/tooltip when when (un)loading the AppIndicator plugin.
=> Some fixes for the tray

blueman/main/NetConf.py
Next up is displaying a nicer error dialog.
```
blueman-mechanism 18.30.36 INFO     NetConf:342 add_ipt_rule: Return code 0
blueman-mechanism 18.30.36 INFO     NetConf:342 add_ipt_rule: Return code 0
blueman-mechanism 18.30.36 INFO     NetConf:342 add_ipt_rule: Return code 0
blueman-mechanism 18.30.36 INFO     NetConf:342 add_ipt_rule: Return code 0
blueman-mechanism 18.30.36 INFO     NetConf:73 do_apply  : ['/usr/sbin/dnsmasq', '--pid-file=/var/rn/dnsmasq.pan1.pid', '--except-interface=lo', '--interface=pan1', '--bind-interfaces', '--except-interface=lo', '--dhcp-range=10.249.217.2,10.249.217.254,60m', '--dhcp-option=option:router,10.249.217.1']
blueman-mechanism 18.30.36 INFO     NetConf:87 do_apply  : dnsmasq: failed to open pidfile /var/rn/dnsmasq.pan1.pid: No such file or directory …
```
=> Netconf nicer error

blueman/main/NetConf.py
This shouldn't actually be a problem, but as long as it's
in there, we may as well set a good example and be pedantic.
This is a minor fixup to #759
=> NetConf.py: explicitly pass "dev" to ip(8) command

apps/blueman-tray.in, blueman/main/PluginManager.py, blueman/main/indicators/AppIndicator.py, blueman/main/indicators/GtkStatusIcon.py, blueman/plugins/AppletPlugin.py, blueman/plugins/BasePlugin.py, blueman/plugins/MechanismPlugin.py, blueman/plugins/ServicePlugin.py, blueman/plugins/applet/AuthAgent.py, blueman/plugins/applet/DBusService.py, blueman/plugins/applet/DhcpClient.py, blueman/plugins/applet/DiscvManager.py, blueman/plugins/applet/ExitItem.py, blueman/plugins/applet/GameControllerWakelock.py, blueman/plugins/applet/KillSwitch.py, blueman/plugins/applet/Menu.py, blueman/plugins/applet/NMDUNSupport.py, blueman/plugins/applet/NMPANSupport.py, blueman/plugins/applet/NetUsage.py, blueman/plugins/applet/Networking.py, blueman/plugins/applet/PPPSupport.py, blueman/plugins/applet/PowerManager.py, blueman/plugins/applet/RecentConns.py, blueman/plugins/applet/SerialManager.py, blueman/plugins/applet/ShowConnected.py, blueman/plugins/applet/StandardItems.py, blueman/plugins/applet/StatusIcon.py, blueman/plugins/applet/TransferService.py, blueman/plugins/manager/PulseAudioProfile.py, blueman/plugins/manager/Services.py
I was looking to always have the parent available for general use [1] and found it was already there as ``__parent__``. 
```
>__parent__ is set in BasePlugin and is actually the Applet, Manager or
Service instances passed in by the PluginManager. However we also pass
these instances to on_load function meaning we may end up adding them
to the plugin twice, once as __parent__ during init and again in on_load.
This also unifies the name "parent" across all plugin bases classes.
```
[1] I am tired of fighting the GDBus service implementation from the pithos folks and make it work with our plugin system. I am looking at doing it differently.
=> Rename __parent__ to parent and make it available to all plugins

blueman/bluez/obex/Manager.py, blueman/main/PulseAudioUtils.py, blueman/plugins/BasePlugin.py, blueman/plugins/applet/NetUsage.py, blueman/plugins/applet/SerialManager.py
I was looking at ``__del__`` usage in plugins. This does not work at all as it is used. Even on proper shutdown we never saw any of the messages printed in ``__del__``.
Commit message explains,
```
This is useful for plugins that need to stop scripts and tear down
things that must always be done. For example kill running scripts like
we do in SerialManager.
We can not rely on __del__ to be run and this is most likely why
SerialManager uses the atexit module. We can howver use weakref to
run a function when the plugin is about tot be deleted.
Now we see the debug message "Deleting plugin instance %s" at shutdown
which never showed for me before.
But, this raises an interesting issue, we never see this message when
disabling a plugin. More work has to be done to properly unload plugins.
``` …
=> Discussion: Usage of __del__ in blueman

blueman/bluez/Base.py, blueman/bluez/Manager.py, blueman/bluez/obex/Client.py, blueman/bluez/obex/Manager.py, blueman/bluez/obex/__init__.py, blueman/main/Sendto.py, blueman/plugins/applet/TransferService.py
Works for me on Gentoo (without systemd) but needs some testing on other ditros.
The TransferService plugin is handled nicely now. It waits for the name ``org.bluez.obex`` to show up before setting up the obex.Manager.
But in blueman-sendto I had to resort to checking the error message for ``StartServiceByName``. The string shows up in the error on a Fedora vm and my gentoo workstation so it should be fairly safe to rely on it.
The best way to test this is to to modify the obex dbus service file. Either set the exec entry to ``Exec=/path/to/obexd`` or ``Exec=/bin/false``.
=> Handle when obexd can not be autostarted

.travis.yml, configure.ac, module/Makefile.am
So this is what is need to get the build working. Why PYTHON_CFLAGS is is being overwritten in travis I have no idea. Normal VM is fine so it probably has something to do with travis.
closes #827
=> Fix travis build for stable branch

blueman/Sdp.py
Magic numbers from https://git.kernel.org/pub/scm/bluetooth/bluez.git/tree/lib/uuid.h
Descriptions from https://www.bluetooth.com/specifications/gatt
As per the commit message, we do not use them but they are used in the dbus api.
=> Add GATT UUIDs en descriptions

blueman/gui/applet/PluginDialog.py, blueman/main/Adapter.py, blueman/main/Sendto.py, blueman/main/Services.py, blueman/plugins/applet/StandardItems.py, data/ui/applet-plugins-widget.ui, data/ui/services-network.ui, data/ui/services-transfer.ui
This turns all dialogs with not parent into normal windows. If there is a parent pass it to the dialog.
I left blueman-sendto as I rather redo it and deal with it then.
This was split from #789 as it is getting too big. There will be another PR for other cleanups.
edit: remove unused import flake8 reported
=> Dialog with no parent

blueman/gui/manager/ManagerDeviceMenu.py, blueman/gui/manager/ManagerProgressbar.py
I am not sure why the device-property-changed signal handler is not connected anymore but it is easy to check so do that instead.
=> A few glib fixes for errors that started to annoy me

blueman/plugins/applet/PPPSupport.py
The timeout is in ms and 0.2 seconds is way too short. The default timeout
works fine for me so drop it alltogether.
=> PPPSupport: Remove timeout from Mechanism.PPPConnect

blueman/main/NetConf.py, blueman/plugins/mechanism/Network.py
We might ask for network setup authorization even if no network settings are configured and we do not actually set anything up. Moving the check in front of the confirmation should avoid that.
Fixes #948
=> Avoid authorization check

blueman/main/Makefile.am, blueman/main/NetworkManager.py, blueman/plugins/applet/DBusService.py, blueman/plugins/applet/NMDUNSupport.py, blueman/plugins/applet/NMPANSupport.py, blueman/plugins/manager/Services.py, data/org.blueman.gschema.xml
Putting my work here as it is mostly done. Still need to clean a few things.
* make sure error and reply handlers are reaching blueman-manager properly
* Handle apn/number changes
* Update the Service manager plugin to show the GsmSettings menu for NMDUNSupport
There is no api exposed over bluez dbus for DUN connection to check if it is actually connected like there is for PANU. It is trivial to get this from NM but afaics we have no functionality to communicate this to blueman-manager. Not sure if it is worth the effort though but if I can figure out a simple way I'll open a separate PR for this.
=> Re-implement PANU and DUN connection through NetworkManager

data/configs/Makefile.am, data/configs/blueman.rules
At least in Arch it seems to be a policy to not change any sources, so its users currently do not get any rules that allow admin users to use privileged features. We now install a default rules file that targets the standard wheel group.
=> Add default polkit rules

CHANGELOG.md, blueman/main/NetConf.py
changes in class_id do not work as I had thought so revert for now
I have been thinking and experimenting with moving ip, netmask and dhcphandler to gsettings. It will move the logic into applet plugins but this is not ready yet for this alpha.
=> Class id is not handle in several places so revert for now

blueman/plugins/applet/DhcpClient.py, blueman/plugins/applet/NMPANSupport.py, blueman/plugins/applet/Networking.py
As discussed in #976 the network icon is not part of the Icon Naming Specification and there is no specific need for it.
=> Change network plugins icons

Dependencies.md
Some time ago I identified elementary-xfce as an additional compatible icon theme. It actually looks like it's currently the only one that provides all of the icon names that we use (mate-icon-theme and gnome-icon-theme e.g. lack `menu-editor`).
=> Add elementary-xfce as compatible icon-theme

blueman/plugins/manager/Info.py, blueman/plugins/manager/Notes.py, blueman/plugins/manager/Services.py
gtk-preferences -> preferences-other
info -> dialog-information
This improves compatiblity with the Icon Naming Specification and themes like adwaita-icon-theme and Papirus (#976)
=> Replace some menu icons

blueman/gui/DeviceList.py, blueman/gui/manager/ManagerDeviceList.py, module/_blueman.pyx
Instead of showing no bars and no way to see if the device is connected or not. We do have something in dbus but these are only available during discovery.
=> Workaround for missing connection info

data/pin-code-database.xml
I verified that the changes in the git log from gnome-bluetooth make sense for blueman. They removed a lot of default pins as BlueZ now handles this through the autopair plugin.
=> Update pindb from gnome-bluetooth

blueman/gui/manager/ManagerDeviceList.py
(Found this while playing with SonarCloud.) The calculation for x is bogus as it is always just a negated 1 / scale. I did not notice any difference (does the negative value fall back to 0?) but I think the intended value is a positive 1 / scale to align with the paired icon.
=> Fix trust icon surface source

apps/blueman-sendto.in, blueman/bluez/AnyBase.py, blueman/bluez/Base.py, blueman/bluez/Device.py, blueman/bluez/obex/Client.py, blueman/bluez/obex/Manager.py, blueman/gui/CommonUi.py, blueman/gui/DeviceList.py, blueman/gui/DeviceSelectorDialog.py, blueman/gui/DeviceSelectorList.py, blueman/gui/DeviceSelectorWidget.py, blueman/gui/GenericList.py, blueman/gui/GsmSettings.py, blueman/gui/GtkAnimation.py, blueman/gui/MessageArea.py, blueman/gui/Notification.py, blueman/gui/manager/ManagerDeviceList.py, blueman/gui/manager/ManagerDeviceMenu.py, blueman/gui/manager/ManagerProgressbar.py, blueman/main/Config.py, blueman/main/DhcpClient.py, blueman/main/Manager.py, blueman/main/PPPConnection.py, blueman/main/PluginManager.py, blueman/main/PulseAudioUtils.py, blueman/main/Sendto.py, blueman/plugins/AppletPlugin.py, blueman/plugins/applet/NetUsage.py, blueman/services/meta/NetworkService.py, blueman/services/meta/SerialService.py
I still need to  pass the parent to a dialog but I need some help with an obex error I am seeing.
Steps to reproduce (after these fixes).
1. Start a largish transfer (so we get the opportunity to stop it on the receiver).
2. Accept the file on the receiver
3. Stop the transfer on the receiver
4. Choose cancel in sendto dialog
This will result in an error removing the session because of invalid argument. But I don't understand why as we pass a proper objectpath to ``RemoveSession``.. :confused: 
```
blueman-sendto 23.57.51 ERROR    Client:39 on_session_remove_failed: /org/bluez/obex/client/session8 org.bluez.obex.Error.InvalidArguments
```
=> Sendto fixes

blueman/plugins/manager/Info.py
The question is whether Class being zero is correct but for now lets make things not crash.
=> Manager Info plugin: Class property is never None

blueman/plugins/manager/Info.py
It will never be None and will always return an int, zero as default.
=> Info Manager plugin: Do not check if Class is None

blueman/plugins/applet/AutoConnect.py, blueman/plugins/applet/Makefile.am, blueman/plugins/applet/RecentConns.py, data/org.blueman.gschema.xml, po/POTFILES.in
Initial draft for #239. It's currently just a "backend" you can configure via gsettings, e.g. `gsettings set org.blueman.plugins.autoconnect services '[("CC:9F:7A:A5:47:34","00000000-0000-0000-0000-000000000000")]'`.
The only useful UUIDs are the above one for auto-connect services (audio, HID) and the specific UUIDs for for other services we can handle (serial, network). Anything else currently causes a crash as `DBusService.connect_service` only expects those UUIDs.
I applied small fixes to the RecentConns plugin on the way. It used a wrapper for the `connect_service` method for no reason and in any case it depends on `DBusService` plugins to be loaded.
=> AutoConnect plugin

Dependencies.md, data/configs/Makefile.am, meson.build
Since D-Bus 1.9.18 configuration files installed by third-party should
go in share/dbus-1/system.d. The old location is for sysadmin overrides.
=> Move D-Bus conf file to share/dbus-1/system.d

blueman/gui/manager/ManagerDeviceList.py, blueman/gui/manager/ManagerDeviceMenu.py
Connect/disconnect with a device can be performed when the user double-clicks on the device. Connect/disconnect labels are bold for the purpose of clarity.
I rebased my repo and changed the code according to the requests (except for https://github.com/blueman-project/blueman/pull/1099#discussion_r324483125 since I didn't understand it. Could you please specify what changes do you expect?).
=> Connect/disconnect on double-click

blueman/plugins/applet/TransferService.py
It has not been created if obex is not running
=> TransferService: Check for an obex manager

apps/blueman-assistant.in, blueman/gui/applet/PluginDialog.py, blueman/main/Services.py
When clicking on Setup... in blueman-manager:
/usr/bin/blueman-assistant:212: PyGTKDeprecationWarning: Using positional arguments with the GObject constructor has been deprecated.
Please specify keyword(s) for "label" or use a class specific constructor. See: https://wiki.gnome.org/PyGObject/InitializerDeprecations
rbs.append(Gtk.RadioButton(service.name))
/usr/bin/blueman-assistant:219: PyGTKDeprecationWarning: Using positional arguments with the GObject constructor has been deprecated.
Please specify keyword(s) for "label" or use a class specific constructor. See: https://wiki.gnome.org/PyGObject/InitializerDeprecations
rbs.append(Gtk.RadioButton(_("Don't connect")))
=> Assistant: Fix PyGTKDeprecationWarnings for Gtk.Button constructor

blueman/gui/applet/PluginDialog.py, blueman/plugins/BasePlugin.py
It could be done with hasattr() but this would be ugly so instead have
a default on the BasePlugin class
```
File "/home/sander/repos/blueman/blueman/gui/applet/PluginDialog.py", line 192, in on_selection_changed
self.author_txt.props.label = cls.__author__ or _("Unspecified")
AttributeError: type object 'AutoConnect' has no attribute '__author__'
```
=> Handle missing __author__ or __description__ in plugins

.circleci/config.yml, module/_blueman.pyx
FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: /home/sander/repos/blueman/module/_blueman.pyx
=> Set proper cython language level to 3

blueman/main/PulseAudioUtils.py
This is @nico202 patch rebased against master so that CI passes. I'll open a PR for stable as well that  contains this and the cython langversion commit.
=> Call the right method when pulseaudio crashes

blueman/main/NetworkManager.py
NMDevice.disconnect shadows the signal handler disconnect
File "/home/sander/repos/blueman/blueman/main/NetworkManager.py", line 83, in _on_device_state_changed
device.disconnect(self._statehandler)
TypeError: argument cancellable: Expected Gio.Cancellable, but got int
=> NetworkManager: Fix disconnecting NMDevice

apps/blueman-assistant.in, apps/blueman-sendto.in, blueman/Functions.py, blueman/main/Adapter.py, blueman/main/Manager.py, blueman/main/PluginManager.py
Passing an exitcode will trigger distributions crash handlers. We really
are expecting to fail so there is no abnormal situation for us.
Also wrap "raise SystemExit" in a function and use it everywhere.
=> Do not use exitcode 1 when we expect to fail

.github/workflows/weblate.yml, po/Makevars
The weblate workflow now uploads blueman.pot as an artifact and re-uses it to avoid timestamp changes on every repository change.
=> Cache blueman.pot

apps/blueman-assistant.in, blueman/gui/GsmSettings.py, blueman/gui/applet/PluginDialog.py, blueman/gui/manager/ManagerDeviceMenu.py, blueman/main/Manager.py, blueman/main/Sendto.py, blueman/main/applet/BluezAgent.py, blueman/plugins/applet/NetUsage.py, blueman/plugins/manager/Notes.py, blueman/plugins/services/Network.py, blueman/plugins/services/Transfer.py
This method is deprecated in Python 3.8 and 3.9, will be removed in 3.10, and appears to be unnecessary in 3.6 and 3.7. The calls got added in https://github.com/blueman-project/blueman/pull/332 to fix an issue where GtkBuilder otherwise uses gettext with the environments' encoding and passes the results to g_markup_escape_text which always expects UTF-8.
The original report reffered to Python 2.7 and a blueman version that used PyGTK, so PyGTK must have called the *Python* gettext() family of functions for the setting to have an effect. When we fixed it, we already used PyGObject and currently we depend on Python 3 which changed the effect to only the lgettext() family of functions, so to still see this PyGObject would have to call the Python lgettext() family of functions. I could not …
=> Drop bind_textdomain_codeset

blueman/main/Adapter.py, blueman/main/Sendto.py, blueman/plugins/applet/ShowConnected.py, blueman/plugins/applet/TransferService.py
msgfmt --check-format does not require format specifications with message keys to be used in the translation, so this gives more flexibility like using "one" instead of an argument containing 1.
=> Use mapping keys for messages with plural forms

blueman/Sdp.py
This is unused as ServiceUUID.name has a special handling for that case.
=> Drop Generic Connect service name

.github/workflows/weblate.yml
Without xgettext blueman.pot-update does nothing and as it is not checked explicitly in configure.ac, this is not detected.
=> Fix Weblate workflow

apps/blueman-adapters.in, apps/blueman-applet.in, apps/blueman-manager.in, apps/blueman-services.in, apps/blueman-tray.in, blueman/Functions.py, blueman/gui/manager/ManagerDeviceMenu.py, blueman/gui/manager/ManagerProgressbar.py, blueman/main/Adapter.py, blueman/main/Applet.py, blueman/main/DBusProxies.py, blueman/main/Manager.py, blueman/main/NetConf.py, blueman/main/Services.py, blueman/main/Tray.py, blueman/plugins/applet/ExitItem.py, blueman/plugins/applet/StandardItems.py, blueman/plugins/applet/StatusIcon.py, blueman/plugins/manager/Services.py, configure.ac, data/configs/Makefile.am, data/configs/org.blueman.Manager.service.in
Apologies for the delay, I started this 2 years ago already :roll_eyes: .
This ports most of the application to use Gio/Gtk.Application. I did the minimal needed so not to break things. But Gtk.Application has lots of benefits which can be used at some later date.
I left the the following as is,
* blueman-sendto: There is no need for uniqueness AFAICS and I rather have it get a redesign.
* blueman-mechanism: We access it through dbus and uses a basic GLib.MainLoop. If the need arises this should be fairly easy to port.
* blueman-assistant: Gtk.Assistant is itself not a Gtk.ApplicationWindow, perhaps in Gtk+4. I could wrap it in a simple Gio/Gtk.Application but we need to think about if we need uniqueness (we currently don't enforce anything, should we?) 
It needs a proper testing to find …
=> Use Gio/Gtk.application and drop check_single_instanced

po/Makevars
This reverts commit fa9ca0f6c4544c74875e78c1945ef94a50b2a7c6.
It turns out Weblate does show locations and as it now squashes updates into a single commit, they should not cause too much fuss.
=> Revert "Disable locations in blueman.pot"

.github/workflows/check.yml, Dependencies.md
* Do not install sudo, python-gi, dh-autoreconf, gtk-update-icon-cache, python3-pip
* Replace intltool with gettext (and autopoint) (also in Dependencies.md)
* Do not install python3-dev in python containers
* Install cython from PyPI
=> Improve workflow job dependencies

.github/workflows/check.yml, apps/blueman-assistant.in, blueman/gui/manager/ManagerDeviceMenu.py, blueman/main/NetworkManager.py, blueman/plugins/applet/AutoConnect.py, blueman/plugins/applet/DBusService.py, blueman/plugins/applet/NMDUNSupport.py, blueman/plugins/applet/NMPANSupport.py, blueman/plugins/applet/PPPSupport.py, blueman/plugins/applet/RecentConns.py, blueman/plugins/applet/SerialManager.py
...and fix some issues.
The ok callback in connect_service and disconnect_service is used in places where it is expected to take no argument (Device.connect, Device.disconnect, SerialService.disconnect, NetworkService.disconnect) or a str argument (service_connect_handler, service_disconnect_handler, explicit call after rfcomm_connect_handler, SerialService.connect, NetworkService.connect). None of the usages of those methods - including the the DBus call due to its empty output signature - actually cares about the argument, so we can unify the signature to a noargs reply handler. ab84869 already dropped the unused reply argument in RecentConns and thus broke it for the serial and network service cases.
The reply value passed on by service_connect_handler, service_disconnect_handler, and …
=> Add type hints to service connection handling

blueman/gui/manager/ManagerDeviceMenu.py, blueman/main/Applet.py, blueman/main/PluginManager.py, blueman/plugins/BasePlugin.py, blueman/plugins/ManagerPlugin.py, blueman/plugins/applet/AppIndicator.py, blueman/plugins/applet/DBusService.py, blueman/plugins/applet/KillSwitch.py, blueman/plugins/applet/NMDUNSupport.py, blueman/plugins/applet/NMPANSupport.py, blueman/plugins/applet/NetUsage.py, blueman/plugins/applet/PPPSupport.py, blueman/plugins/applet/PowerManager.py, blueman/plugins/applet/RecentConns.py, blueman/plugins/applet/SerialManager.py, blueman/plugins/applet/ShowConnected.py, blueman/plugins/applet/StandardItems.py, blueman/plugins/applet/StatusIcon.py, blueman/plugins/manager/Info.py, blueman/plugins/manager/Notes.py, blueman/plugins/manager/PulseAudioProfile.py, blueman/plugins/manager/Services.py
Use mixins for dynamically defining functionality instead of dynamically adding it to / removing it from the AppletPlugin and dynamically calling it. PluginManager now only provides a convenience way of getting loaded plugins that are instances of a specific mixin and calls are done directly without any necessity for fancy call handling as the caller can do whatever it wants to do directly.
Depends on #1329 (due to many conflicting code locations) and currently does not work due to circular dependencies at least between StatusIcon and PowerManager.
=> Refactor inter-plugin callback handling

CHANGELOG.md, blueman/bluez/obex/Client.py, blueman/gui/manager/ManagerDeviceList.py, blueman/gui/manager/ManagerProgressbar.py, blueman/main/Manager.py, blueman/main/applet/BluezAgent.py, blueman/plugins/manager/Info.py
Some actual fixes for issues found while adding type hints, cherry-picked from #1338 #1340 #1341.
=> Fixes from type hints

CHANGELOG.md, blueman/bluez/Adapter.py, blueman/bluez/Base.py, blueman/gui/DeviceList.py, blueman/main/Manager.py
The _call method is basically used in two ways:
* Make an asynchronous call, providing a reply and an error handler for when it's done
* Make a call whose result we do not care about, providing no handlers.
In the latter case, we also do an asynchronous call which makes sense as the caller does not have to wait for it (might be an issue, though, as he might expect the call to already have an effect when the method returns). However, raising an exception when we get an error for that call does not make any sense at it will just get raised into the main loop (and get picked up by tools like Apport or ABRT), so best we can do here is just log the error and the call we got it for.
More involved solutions would be to either make the error_handler argument mandatory so that the caller has to …
=> Handle unexpected DBus errors

blueman/gui/applet/PluginDialog.py, blueman/main/Adapter.py, blueman/main/Applet.py, blueman/main/Config.py, blueman/main/DBusProxies.py, blueman/main/DbusService.py, blueman/main/DhcpClient.py, blueman/main/Manager.py, blueman/main/MechanismApplication.py, blueman/main/NetConf.py, blueman/main/NetworkManager.py, blueman/main/PPPConnection.py, blueman/main/PluginManager.py, blueman/main/PulseAudioUtils.py, blueman/main/Sendto.py, blueman/main/Services.py, blueman/main/SpeedCalc.py, blueman/main/Tray.py, blueman/main/applet/BluezAgent.py, blueman/main/indicators/AppIndicator.py, blueman/main/indicators/GtkStatusIcon.py, blueman/plugins/BasePlugin.py
Depends on #1332 (probably for no good reason :see_no_evil:)
=> Add type hints to blueman.main 

.github/workflows/check.yml, blueman/services/meta/SerialService.py
We're basically mypy --strict now, just --disallow-subclassing-any is missing as all the untyped GLib / Gtk classes we inherit from are considered Any. This can be fixed by adding stubs for them which will reveal all kinds of edge cases I guess.
Depends on #1338 #1340 #1341.
=> Enable mypy --disallow-untyped-calls --disallow-untyped-defs

CHANGELOG.md, Dependencies.md
With the use of gtk_menu_popup_at_pointer we actually require 3.22
=> Update GTK+ 3 dependency

README.md
The conclusion we draw there seems to be questionable. The only hint about the icons' license is the license attribute in their code that points to https://creativecommons.org/licenses/GPL/2.0/ which redirects to https://www.gnu.org/licenses/old-licenses/gpl-2.0.html. Neither of the URLs distinguishes between version 2 with or without "any later version", see https://wiki.creativecommons.org/wiki/License_Properties#Source_Code_Licenses and https://www.gnu.org/licenses/#LicenseURLs. The license text says:
> If the Program specifies a version number of this License which applies to it and "any later version", you have the option of following the terms and conditions either of that version or of any later version published by the Free Software Foundation.
As the URLs do not distinguish, it …
=> Remove misleading license statement

blueman/gui/GenericList.py, blueman/gui/manager/ManagerDeviceList.py, blueman/main/Services.py
The TreeIter can actually be None and GenericList.compare can actually handle that while ManagerDeviceList._on_popup_menu and BluemanServices.on_selection_changed expect a proper TreeIter.
Fixes #1420
=> Fix GenericList.selected

blueman/gui/DeviceList.py
The discovering state shadows the adapter's actual state and its usage is broken, e.g. when we handle a property change where the adapter stopped discovering, we try to stop the discovery again which fails of course.
=> Remove weird state handling from DeviceList

blueman/gui/manager/ManagerDeviceMenu.py, po/blueman.pot
BlueZ obtains most of those messages from strerror, passing more or less appropriate error codes chosen by itself (e. g. ENOPROTOOPT for missing audio endpoints) or obtained from the kernel, which, amongst other things, translates Bluetooth error codes to more or less appropriate error codes in `bt_to_errno` (e. g. page / advertising timeouts to EHOSTDOWN).
By matching those messages to what is expected from glibc, uClibc, and musl we can use our own messages to clarify the context and localize them (strerror and and other BlueZ error messages are not localized).
See #1363 for the selected errors. Others do not seem relevant.
=> Translate common error messages and ignore cancelled error

blueman/gui/manager/ManagerDeviceMenu.py, po/blueman.pot
A typical occurrence is when pairing gets cancelled while connecting to an unpaired audio device but there are other occurrences related to BlueZ / driver / firmware issues (see #650) and it can always hint at generic unexpected (audio) connection errors similar to EIO.
Closes #1363
=> Translate EAGAIN

blueman/gui/DeviceList.py
#1433 was wrong. The `discovering` property's is not there to represent the discovering state but to control the progress update. When it gets set to False, `update_progress` stops. We cannot use the actual discovering state of the adapter as it might not have been set yet right when we start the progress and we cannot just drop the check as we keep emitting `discovery-progress` events then if the discovery was not stopped by the timeout, so we need such a control property.
=> Fix discovery state handling

CHANGELOG.md, blueman/plugins/applet/DiscvManager.py, po/blueman.pot
I realized that this menu item was constantly missing if blueman-applet started with Bluetooth disabled. The reason is simply that the plugin checks the availability of an adapter when the D-Bus object manager becomes available or when the current adapter gets removed but not if an adapter gets added. It thus only shows the item if an adapter is available already when the object manager becomes available and only until it gets removed.
=> Handle added adapters in DiscvManager

CHANGELOG.md, blueman/main/applet/BluezAgent.py, po/blueman.pot
DisplayPasskey is mainly used for pairing KeyboardOnly devices (a.k.a. Bluetooth keyboards) but might also get called if we are the initiator of a legacy pairing to a KeyboardDisplay device. This improves several aspects of the implementation:
* Add padding to avoid showing incomplete passkeys.
* Use the provided information of how much of the passkey has already been entered to guide the user while typing.
* Avoid adding more and more notifications while typing by closing and thus replacing the previous one.
The implementation assumes that `entered` is at most 5 and `Cancel` gets called when the sixth digit got received. Unfortunately I do not have a KeyboardOnly or pre Bluetooth 2.1 legacy device to test if that's actually the case (... and looking at the kernel source I fear that it …
=> Improve passkey handling

CHANGELOG.md, blueman/gui/manager/ManagerDeviceList.py, blueman/gui/manager/ManagerMenu.py, data/org.blueman.gschema.xml, po/blueman.pot
I don't like the menu entry name but at 1 in the morning I am out of ideas :sleepy:. If you have a suggestion feel free to comment.
=> ManagerDeviceList: Hide devices with no name

blueman/gui/manager/ManagerDeviceList.py, blueman/gui/manager/ManagerDeviceMenu.py
When right clicking on a device, nothing happens. It turns out the code is in-place to show some rather useful menus. However, popup menus need to have a parent to be drawn:
```
Gdk-Message: 14:55:46.423: Window 0x55ee0e347360 is a temporary window without parent, application will not be able to position it on screen.
(blueman-manager:459528): Gdk-CRITICAL **: 14:55:46.427: gdk_wayland_window_handle_configure_popup: assertion 'impl->transient_for' failed
```
This tiny change fixes the issue. I'm no terribly familiar with Gtk, but some quick research indicates that this seems to be the recommended approach for this for contextual popup menus.
I've tested this and it works fine. Most of the hard work was done TBH.
- Double clicking or right clicking on a device does nothing.
- Right …
=> Fix popup menus no rendering

blueman/Service.py, blueman/plugins/manager/Services.py, blueman/services/DialupNetwork.py, blueman/services/meta/NetworkService.py, blueman/services/meta/SerialService.py, po/POTFILES.in, po/blueman.pot
This is split off from #1414 to get it rolling.
* Remove serial service submenu from device menu
The submenu seems rather pointless and random. It is only used if a DUN and / or multiple serial services are available. In the most usual case it only holds a connect item for the DUN service and the settings item. Disconnect items do not get added to the submenu.
* Replace connected with connectable as it is already misused as "not connectable" (serial services return False even if they are connected as they are still connectable). (Note that "connectable" is independent of "available" as it is used to show disabled connect items).
* Add connected_instances to provide per-service disconnect items.
* Add common_actions to provide actions that shall be shown if any of the services specifies …
=> Improve service interface and Services plugin

CHANGELOG.md, blueman/Sdp.py, blueman/config/AutoConnectConfig.py, blueman/config/Makefile.am, blueman/gui/manager/ManagerDeviceMenu.py, blueman/plugins/manager/Info.py, blueman/plugins/manager/Notes.py, blueman/plugins/manager/PulseAudioProfile.py, blueman/plugins/manager/Services.py, po/POTFILES.in, po/blueman.pot, stubs/gi/repository/Gtk.pyi
The first four commits are refactoring and improvements for the service interface and menu handling.
Then comes the actual implementation for https://github.com/blueman-project/blueman/issues/239#issuecomment-375131266 - finally :tada:. As the wizard is no more, menu items seem like the only logical place to do this. The last commit is kind of an optional idea to keep the menu lean, but I think it makes sense. The only downside I see is that people might not open the menu a second time after connecting a service when looking for a way to auto-connect.
=> Add auto-connect items to device menu

blueman/plugins/applet/AutoConnect.py, po/blueman.pot
Triggered when Bluetooth gets unblocked or a new adapter gets added. We do not have to wait for the timer in those situations.
#1466
=> AutoConnect: Run when new adapters become available

blueman/main/NetConf.py
This NetConf stuff is a mess... I somehow ended up without those attributes in /var/lib/blueman/network.state which can easily happen if store gets called before any call to set_ipv4 and the resulting object is completely unusable (get_default already fails, set_ipv4 would fail, so it can never get a configuration, and so so...)
=> Define NetConf attributes in __init__

.github/workflows/check.yml
The default official Python docker images switched to bullseye recently where iproute2 needs to get installed for ./configure to succeed and libappindicator has been replaced with libayatana-appindicator so that the tests will not work. We thus fix them to buster for now.
=> Fix workflows

blueman/plugins/manager/Services.py
If we have multiple common actions (i.e. dialup settings and IP address renewal) we use one of the callbacks for all menu items.
=> Fix handling of common service actions

blueman/main/PluginManager.py, blueman/plugins/Makefile.am, blueman/plugins/applet/GameControllerWakelock.py, blueman/plugins/errors.py, po/blueman.pot
I get the errors from #1461 a lot so I thought I'd try to quiet them a little bit.
There is no sensible way to implement this feature on Wayland atm, so the behavior stays the same. The only difference is the logging, which will change this
```
blueman-applet 13.56.12 ERROR    PluginManager:90 load_plugin: Unable to load plugin module GameControllerWakelock
File "/usr/lib/python3.9/site-packages/blueman/main/PluginManager.py", line 88, in load_plugin
importlib.import_module(self.module_path.__name__ + f".{plugin}")
File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
File "<frozen importlib._bootstrap>", line …
```
=> Be quieter about plugin failures on Wayland

blueman/plugins/applet/RecentConns.py
* Rename initialize to _rebuild, include logic to change sensitivity and call whenever necessary
* Rename add_item to _build_menu_item and remove unnecessary logic
* Add on_device_created
* Modify recent-connections options directly in notify and rebuild menu
* Rename items to _get_items and do not cache
=> Refactor RecentConns

blueman/plugins/applet/StatusIcon.py
When turning bluetooth on using the applet the tray status icon flickers (disappears the re-appears). This is annoying when a user opens a menu when the visibility is set, the context menu freezes and covers that part of the screen. It cannot be closed only by killing the blueman-applet process.
It seems to me, that turning the BL on, takes time for the power manager, so I've increased the delay.
```
blueman-applet 14.58.20 INFO     KillSwitch:106 io_event  : killswitch registered 31
blueman-applet 14.58.20 INFO     KillSwitch:122 io_event  : State: True
blueman-applet 14.58.20 INFO     PowerManager:178 update_power_state: off False | foff False | on True | current state True | new state True
<wait 1-2 seconds>
blueman-applet 14.58.21 DEBUG    Manager:42 _on_object_added: /org/bluez/hci0 …
```
=> Increase status icon visibility timeout

blueman/plugins/manager/Notes.py
This fixes the cancel button in the send note dialog.
To reproduce the issue:
- Choose a device in the manager
- Send a note
- Press the cancel button
The note is sent instead of being cancelled.
The glade file note.ui defines the cancel button action as a REJECT action. This was misinterpreted in the python source code.
=> Manager: Fix cancel button in send-note dialog

data/ui/manager-main.ui
Most themes render toolbars the same way no matter where the toolbar is located in the window. Some themes style the "primary" toolbar differently though to make it look flush with the titlebar.
Since blueman's toolbar is located just under the menubar/titlebar, it should be styled as "primary-toolbar" to let themes know how to render it.
Here's an example with the Arc theme.
Before:
After:
=> Manager: Assign primary-toolbar style to main toolbar

CHANGELOG.md, blueman/Functions.py
The size of struct ifreq is dominated by the size of struct ifmap whose size depends on two long fields, so that it is actually just 32 bytes on 32 bit systems.
Fixes #1618
=> Fix network interface iteration on 32 bit systems

.github/workflows/release.yml
Otherwise the configure script will not work for Python 3.10.
I already re-built and re-released https://github.com/blueman-project/blueman/releases/tag/2.2.4 with this.
=> Use a recent automake for release packages

blueman/gui/manager/ManagerProgressbar.py
- Add a bit of space between the bar and the cancel button
- Fix the visibility of the progressbar label
=> UI: Improve look of progressbar

blueman/gui/Notification.py
The method can be used to replace the message especially of already shown notifications. _NotificationBubble.show() does keep track of the notification ID and uses the D-Bus protocol's replacing capabilities, so that we can just re-call it to replace an already shown notification. In case of _NotificationDialog it is sufficient to just set the property, no matter if the dialog is already shown or not.
=> Add Notificaton.set_message

blueman/gui/Notification.py, blueman/plugins/applet/ConnectionNotifier.py
I really don't like the generic delay of 5 seconds for all connection notifications. This is a quick draft to show instant notifications and update them with battery levels for up to five seconds instead.
It works fine in a quick test, however, when the device just got connected, it does not have the battery (percentage) yet, so that line 37 always fails. `_on_battery_created` does update the message as expected but this breaks the icon logic as the battery icon will never be used. Not sure if a way to update the icon is the way to go there or not. I also could not actually test the `property-changed` signal.
=> Update instead of delaying connection notifications

blueman/gui/manager/ManagerDeviceMenu.py
FIxed connect and disconnect menu entries having an `_` prefixed.
=> ManagerDeviceMenu: Fix (dis)connect accelerators

.github/workflows/check.yml, .github/workflows/potfile.yml, .github/workflows/release.yml, .github/workflows/weblate.yml
A more recent version of automake is required for Python 3.10 compatibility.
=> Use ubuntu-22.04 for all jobs that run autogen.sh

.github/workflows/check.yml, .github/workflows/potfile.yml, .github/workflows/release.yml, .github/workflows/weblate.yml, configure.ac
Not sure how you tested this before..
The problem with the current approach is that it can easily miss including automake files that are in the dev package. For example the 2.3 tarball from the release job are broken as it does not include the gsettings automake parts.
ps: I uploaded 2 new files which pas distcheck.
=> Use make distcheck to provide tarball(s)

blueman/main/indicators/StatusNotifierItem.py
In lxqt-panel.  GetLayout is called twice.  Once with parent_id = 0, then parent_id = 7(recent connections).  But it doesn't rebuild the recent connection submenu only the menu item.
I am using lxqt-panel v1.1.0
=> Recent connections menu is missing in lxqt-panel

blueman/main/indicators/StatusNotifierItem.py
xfce4-panel assumes true as a default here as because otherwise it would just try the possibly failing activation if the property is not set.
Closes #1805
=> Set ItemIsMenu

CHANGELOG.md, blueman/Functions.py, blueman/plugins/applet/PowerManager.py, data/org.blueman.gschema.xml
I think this feature does more harm than good nowadays.
BlueZ introduced a similar `AutoEnable` option in 5.35. At least Debian and its derivatives enable it by default. Distros that love upstream configurations like Arch Linux did not but [BlueZ 5.65 finally changed the default](https://git.kernel.org/pub/scm/bluetooth/bluez.git/commit/?id=180cf09933b2d8eb03972c8638063429fe5fece5).
Compared to `AutoEnable` `auto-power` has some non-desirable differences in behavior: At least it does not cover suspend and resume, see #1555, and together with the `KillSwitch` plugin it overrides killswitches as the plugin tries to unblock them when powering is requested.
=> Drop auto-power

CHANGELOG.md, blueman/main/indicators/GtkStatusIcon.py, blueman/main/indicators/StatusNotifierItem.py, blueman/plugins/applet/Menu.py, blueman/plugins/applet/PowerManager.py, blueman/plugins/applet/PulseAudioProfile.py, blueman/plugins/applet/RecentConns.py
Re-using identifiers e.g. for separator and standard menu items triggers bugs at least in gnome-shell-extension-appindicator (#1845).
As a workaround we can just use the toplevel items' priority values instead of sequential identifiers to get unique identifiers for all items.
To do that the MenuItem's priority value gets added as `id` to the MenuItemDict serialization and picked up by the IndicatorInterface implementations. Note that the semantics of the first argument ot the MenuItemActivator change accordingly.
=> Do not re-use dbusmenu item identifiers

CHANGELOG.md, blueman/main/indicators/StatusNotifierItem.py, blueman/plugins/applet/Menu.py, blueman/plugins/applet/RecentConns.py
Other applets like NetworkManager's do not try to keep menu small, so why should blueman...
Closes #1558
This was lying around for a while now. I'm not happy with the presentation yet and don't have any better idea for it but in general this should be good.
=> Put recent connections in toplevel applet menu

CHANGELOG.md, blueman/main/indicators/StatusNotifierItem.py
KDE Plasma expects this method to be implemented. Otherwise it just does not show submenus.
Closes #1856
=> Implement com.canonical.dbusmenu.AboutToShow

blueman/plugins/applet/DisconnectItems.py, blueman/plugins/applet/PulseAudioProfile.py
With #1847 priorities are expected to be unique. Otherwise the items get merged into one, so that there is only one disconnect and only one audio profile item as no explicit sub-indexes got added there.
Fixes #1861
=> Fix per-device applet menu items

blueman/plugins/applet/Menu.py
#1847 added an integer type check in front of the boolean type check and as booleans are a subset of integers in Python boolean values not get serialized as integers as well. This does not break anything as the resulting integer values just get used as boolean but SonarCloud catches the dead code (now; I do not know why it did not earlier...).
=> Fix menuitem serialization

blueman/main/Tray.py, blueman/main/indicators/GtkStatusIcon.py, blueman/main/indicators/StatusNotifierItem.py
Earlier we just re-registered our item when a new StatusNotifierWatcher showed up but there are actually three cases where this happens:
* In case the watcher got replaced. This is what #1801 actually targeted and works fine for.
* Initially if a watcher is available. This means we actually register the item twice: Directly from within the constructor and from the handler. Does not hurt but is unnecessary.
* In case a watcher actually just showed up. In this case, we are already using the GtkStatusItem fallback, though, and this thus leads to two icons, see #1870.
Instead of re-registering, this change causes blueman-tray to reload if a watcher appears after we failed to register the item or a watcher appears for the second time.
=> Improve handling for new StatusNotifierWatcher

blueman/gui/applet/PluginDialog.py, blueman/plugins/applet/AuthAgent.py, blueman/plugins/applet/DBusService.py, blueman/plugins/applet/KillSwitch.py, blueman/plugins/applet/NMDUNSupport.py, blueman/plugins/applet/PowerManager.py, blueman/plugins/applet/StandardItems.py, blueman/plugins/applet/StatusIcon.py
This provides a solution for #1495 / (#949), however, if a user disables the plugin from the UI, there will be no obvious way for him to re-enable it again (GSettings works, of course).
=> Make StatusIcon plugin unloadable

blueman/plugins/applet/GameControllerWakelock.py
Or we fail to start blueman-applet, see
https://bugs.gentoo.org/874615
=> GameControllerWakelock: Handle missing GdkX11 gracefully

blueman/plugins/applet/PulseAudioProfile.py, blueman/plugins/applet/StatusNotifierItem.py
AudioProfiles and StatusNotifierItem do not actually depend on it. They are rather pointless without a status icon but they do work. Also there is no point in not making AudioProfiles unloadable (the default). This makes #1496 actually work.
=> Fix dependencies on StatusIcon plugin

CHANGELOG.md, blueman/main/indicators/StatusNotifierItem.py, blueman/plugins/applet/Menu.py, configure.ac, meson.build
1297d8806e416f90a4dd0bfcef6e76849ef65675 requires this to be available but it is not as it is part of #1652. This backports the relevant changes.
Fixes #1887.
=> Add missing multi-level ID support for menu items

blueman/main/Applet.py, blueman/main/PluginManager.py, blueman/plugins/applet/DisconnectItems.py, blueman/plugins/applet/RecentConns.py, blueman/plugins/applet/StatusIcon.py
This is rather ugly, especially as it breaks the dynamic nature of the PluginManager and involves a cast, but it is definitely an improvement as it would have caught #1887 early (would need backporting to 2-3-stable for that of course - RecentConns is ugly).
There might be some generic way of defining this, like `__getattr__(self, key: Literal[_T]) -> _T` but I did not find a way to actually express something like "literal name matching a typevar's value".
=> Define relevant plugin types for BluemanApplet.Plugins

CHANGELOG.md, blueman/main/NetConf.py, test/main/test_netconf.py
* Set router address as DNS server instead of loopback addresses
* Enable dnsmasq DNS service if possible and add DNS servers otherwise
Based on and includes #1564
=> Improve DNS server handling in DHCP handlers

blueman/gui/manager/ManagerDeviceMenu.py
If the right click instance has never been used and the user double clicks to connect it will not have a SelectedDevice yet.
=> ManagerDeviceMenu: Do not assume all instances have been generated

blueman/gui/manager/ManagerDeviceList.py, data/icons/hicolor/scalable/emblems/Makefile.am, data/icons/hicolor/scalable/emblems/blueman-connected-emblem.svg
This could solve the problem mentioned in #1642 as an alternative to the #1620 concept.
I think it's fair to just use the spot of the "paired" emblem and override it with the "connected" emblem. It's not very distinguishable right now, though. One might probably want a different color for it. 
The icon's content is basically stolen from Adwaita.
=> Add emblem for connected state

configure.ac, meson.build
I was properly confused when I looked at the version in blueman being 2.3 while I was (almost) certain I was using the a git build from a couple days ago. Happy to change it to something else if alpha is not right.
=> Bump version to an alpha

blueman/bluez/Device.py, blueman/gui/DeviceSelectorList.py, blueman/gui/manager/ManagerDeviceList.py, blueman/main/Manager.py, blueman/main/NetworkManager.py, blueman/main/Sendto.py, blueman/main/applet/BluezAgent.py, blueman/plugins/applet/AutoConnect.py, blueman/plugins/applet/ConnectionNotifier.py, blueman/plugins/applet/DisconnectItems.py, blueman/plugins/applet/NetUsage.py, blueman/plugins/applet/PPPSupport.py, blueman/plugins/applet/PulseAudioProfile.py, blueman/plugins/applet/RecentConns.py, blueman/plugins/applet/SerialManager.py, blueman/plugins/applet/TransferService.py
I encountered an interesting device that has a trailing CR on its Name and default Alias, causing weird looking empty lines at least in our device list and the status icon menu items. Of course there could be more such garbage (like control characters somewhere in the middle of a name), but stripping surrounding whitespace in all places where an Alias shows up in UI seems like a low hanging fruit here.
=> Strip surrounding whitespace from device names

blueman/gui/DeviceList.py
10ish seconds is not enough for certain devices to be found.
=> Increase device scan timeout

blueman/gui/DeviceList.py
As seen in https://bugzilla.redhat.com/show_bug.cgi?id=2148624, it looks like at least our fader can cause the device removal event to get handled multiple times, so that the tree_iter might actually be gone and the assertion causes an exception. If there is no tree_iter, there is nothing left that we could or should do, so we can just return.
=> blueman-manager: Handle device removal events gracefully

blueman/gui/manager/ManagerDeviceList.py
I noticed the devicemenu going insensitive and the buttons on the toolbar changing while no selection changed.
=> ManagerDeviceList: emit device-selected once on device removal

blueman/plugins/applet/SerialManager.py, blueman/services/meta/SerialService.py, module/_blueman.pyx
Just quick draft so we can discuss if we need to display something to the user or not. And logging the exception may be too much, perhaps just the error message with or without the error number?
=> Handle rfcomm_list failing

blueman/bluez/AnyBase.py, blueman/bluez/Base.py
So we can get to the invalidated properties.
Base will now add the list of invalidated properties like this.
```python
Base:67 __properties_changed: /org/bluez/hci0/dev_76_DD_19_54_A8_42 {} ['TxPower', 'RSSI'] <Device.Device object at 0x7f777e155e80 (blueman+bluez+Device+Device at 0x55ef15d47da0)>
```
=> bluez.Base: Don't subclass from Gio.DBusProxy

blueman/gui/manager/ManagerMenu.py, blueman/gui/manager/ManagerStats.py, data/ui/manager-main.ui
Before it would jump back and forth depending on the rate. It is still possible for it to grow when enough data is transferred but no jumpy stats every couple of seconds.
edit: gave it a bit more space, hopefully this is enough for it to never jump even when a lot of data has transferred.
=> Move widget creation to UI file and give stats enough space to grow and shrink

blueman/gui/manager/ManagerDeviceList.py
Ignore the other commit (it's bed time so I left it in).
How about we handle the surface like this? When I added the scaling I wasn't smart enough to figure out how to get the surface in the store. It's not perfect but it works well enough and simplifies things.
=> Wrap cairo.Surface in a GObject

CHANGELOG.md, blueman/main/DBusProxies.py, blueman/plugins/applet/StandardItems.py
This is inconsistent with the other blueman application and can be confusing.
=> StandardItems: Do not close blueman-manager on activate via applet

CHANGELOG.md, blueman/bluez/Battery.py, blueman/main/BatteryWatcher.py, blueman/main/Makefile.am, blueman/plugins/applet/ConnectionNotifier.py, blueman/plugins/applet/ShowConnected.py
Issues: `BatteryWatcher`'s users expect it to get destroyed and for that `BatteryWatcher` expect the `Manager` and `Battery` objects to get destroyed. The latter requires #1908 to actually happen and for `Manager` it does not work due to the `self`-references it passes to its signal handlers to be able to call its `emit` method. I'm not sure if and how that could get resolved.
Apart from that I'm not sure how good the idea of using that Unicode symbol actually is... :sweat_smile:
=> List devices and battery levels in status icon tooltip

CHANGELOG.md, sendto/blueman_sendto.py.in
nautilus 0.43 / nautilus-python 4.0 dropped the window argument:
https://gitlab.gnome.org/GNOME/nautilus/-/commit/bc55ff7599ef7f5acc6e9b648765fdb45b56431c
https://gitlab.gnome.org/GNOME/nautilus-python/-/commit/fac72de53ba7a102b22b64976bc49f68c97c23f7
Closes #2134
=> Adapt sendto extension for recent nautilus

blueman/gui/applet/PluginDialog.py, data/ui/applet-plugins-widget.ui
The main change is that the author, conflicts and depends moved to the bottom and arranged horizontal. This also makes space to perhaps show the settings instead of having button to switch.
Before
After
=> Improve PluginDialog

blueman/main/Tray.py
Depening on timing we may never send a reply to the caller if we restart immediately.
=> Tray: Let dbus call end and reply to caller

CHANGELOG.md, blueman/gui/manager/ManagerMenu.py, blueman/plugins/applet/DBusService.py, data/ui/manager-main.ui, stubs/gi/repository/Gtk.pyi
This also does not disable the whole "Adapter" menu, so that the exit item is now reachable when powerd off.
Closes #2044
=> Allow to toggle the Bluetooth status from the manager menu

blueman/gui/manager/ManagerDeviceList.py, blueman/gui/manager/ManagerDeviceMenu.py, blueman/gui/manager/ManagerMenu.py, blueman/gui/manager/ManagerToolbar.py, blueman/plugins/manager/Info.py, blueman/plugins/manager/Notes.py, blueman/plugins/manager/PulseAudioProfile.py, blueman/plugins/manager/Services.py
Toolbar: Disable search and send buttons if the adapter is not powered (unpaired devices should not be present anyway).
Device menu: Do not add the following if not powered:
* Connect items
* Send file
* Send note
=> Respect adapter power state in manager

blueman/gui/applet/PluginDialog.py, data/ui/applet-plugins-widget.ui, stubs/gi/repository/GObject.pyi
I still see some weirdness with enabling/disabling plugins but I suspect I messed up my gsettings in the process. Putting it out here as a possible option to use for blueman-manager's device list.
The idea here is that we make our own widget in the factory function and then optionally bind the GObject property to widgets. Then updating the `GObject` property will automatically update the UI. The plugin dialog is not very dynamic and used stateful `SimpleAction` for the checkbox but binding the enabled property is also an option.
mypy was very unhappy so some of the typing annotation looks weird and I had to cast the `PluginItem` properties to convince it.
The other option is to use `ListBoxRows` and insert them manually into the `ListBox`.
=> Listbox for plugindialog

test/bluez/obex/test_imports.py, test/bluez/test_imports.py, test/gui/applet/test_imports.py, test/gui/manager/test_imports.py, test/gui/test_imports.py, test/main/applet/test_imports.py, test/plugins/services/test_imports.py, test/plugins/test_imports.py, test/services/meta/test_imports.py, test/services/test_imports.py, test/test_imports.py
Python 3.11 deprecated returning values from test functions which the lambda does.
=> Fix deprecations in tests

blueman/main/Adapter.py
It get's really confusing which adapter a user is modifying when it just shows what BlueZ initially set. BlueZ uses the hostname as name and subsequent adapters appends `#N`.
=> Show hci device in tab label

blueman/gui/manager/ManagerStats.py, blueman/main/Manager.py, blueman/plugins/applet/PowerManager.py
The function is completely unreliable regarding its option to turn Bluetooth on and regularly leads to closing the application while doing so (#1119 #2161). Also, the whole system is incosistent as while it avoids starting blueman-manager with Bluetooth powered off, you can absolutely run blueman-manager with Bluetooth powered off e.g. simply by turning it off while it's open (#1707). There is even a menu item for turning Bluetooth off (and back on!) now.
Fun fact: Turning Bluetooth off while blueman-manager is running is actually meant to lead to the same dialog (and should have in 2.0), but #543 broke the signal handling: Since 2.1 `status` is set to a 1-tuple returned by `unpack` instead of a `bool` and the tuple is always `True`ish.
Note: blueman-adapters suffers from the same …
=> Remove check_bluetooth_status from blueman-manager

blueman/main/Manager.py, data/ui/manager-main.ui
I would have liked to show the state of the adapter and the killswitch. While getting the adapter state is easy, the state of the killswitch is not. So for now get the global state from the applet.
I'll rebase when the PR for the dialog is merged.
=> Add bluetooth status icon in the statusbar

blueman/gui/manager/ManagerDeviceList.py
Loading the surface directly from the Gtk.IconTheme raises an GError. We lookup the icon first like we used and check for None like we used to.
This is what would have happened before I reworked how blueman stores the surface. I'll open a PR for main later.
=> ManagerDeviceList: Fix broken fallback in _load_surface

blueman/plugins/applet/ConnectionNotifier.py
I'm baffled why the user in #2304 isn't getting the property change when the device connected. We still need to not crash so let's fix this now.
=> ConnectionNotifier: Don't crash when there was no prior notification

blueman/main/indicators/StatusNotifierItem.py
kded6 provides an `org.kde.StatusNotifierWatcher` service without its usual `/StatusNotifierWatcher` object if Plasma Workspace's StatusNotifierWatcher module is registered but not loaded (https://invent.kde.org/plasma/plasma-workspace/-/merge_requests/3301). We thus cannot just assume the whole service to be unavailable if the registration fails as we restart the tray application when the name appears.
This is a problem if the Plasma Workspace is around especially on i3 where no other application registers `org.kde.StatusNotifierWatcher`.
Closes #2311
=> Handle incomplete StatusNotifierWatchers

CHANGELOG.md, configure.ac, meson.build
I plan to a add a note on icon themes to the release description on GitHub. Something like:
Note to maintainers: We found that the Adwaita Icon Theme dropped most non-symbolic icons in version 44, so that it can no longer be considered a generic fallback for GTK. blueman with just Adwaita Icon Theme will show a lot of missing icons. We are still puzzled by this change and try to figure out what to do. You can jump in at #2312. In the meantime, make sure that your packages depend on proper icons themes.
=> Prepare 2.4.1

test/main/test_dns_server_provider.py
This allows the DBus mock server to be properly torn down once the tests are done running. DBusTestCase inherits from unittests' TestCase, so this remains functionally the same.
Without this patch, I was experiencing CI timeouts on Alpine Linux's package builders.
(will also need to be backported to 2.4)
=> Inherit from DBusTestCase directly in DNS provider test

blueman/plugins/applet/Menu.py, blueman/plugins/applet/PulseAudioProfile.py
We build a (32 bit) ID for the menu item from its priority values, using the sub priority as the lower 8 bits. Pulseaudio card indexes are theoretically 32 bit and PipeWire re-assignes them with large gaps on re-connect so that it provides high 3-digit numbers in practice that do not fit the 8 bits.
Closes #2331
=> Fix audio profile menu item priorities

blueman/plugins/applet/ConnectionNotifier.py
From feedback in #2317 it became pretty clear that battery data is a mess with devices providing levels like full, medium, low and devices providing fine-grained percent values, flapping values etc. and we do not want to go into power management applet business, so we only show a single battery notification on connection (when the battery interface shows up or - if the interface is already present when the device connects - when the existing interface sends its first property update) and drop the reference to the connection notification to update so that further values do not lead to a notification. (In case people will ask for those notifications we might add them as a separate plugin that's disabled by default.)
Due to the great demand, I plan to backport this for 2.4.2, even though …
=> Only show a singly battery notifcation

blueman/plugins/applet/RecentConns.py
I hope this makes things clearer and avoids confusion due to the change from 2.3 to 2.4.
Closes #2328
=> Rename recent connections header

blueman/plugins/applet/RecentConns.py
For example in the StatusNotifierItem.
fixes #2429
=> RecentConns: Alias may contain < > which causes parse errors

blueman/main/DBusProxies.py
Non testing version of #2384.
This is a good idea regardless if it solved the problem or not.
=> DBusProxies: Make method calls asynchronous

blueman/plugins/applet/AutoConnect.py
Something like this? Or would you like a different approach.
=> AutoConnect: Automatically convert path to address

blueman/plugins/mechanism/Rfcomm.py, blueman/services/meta/SerialService.py
=> Rfcomm: Change dbus type signature to an int

module/meson.build
build systems like OE build outside sourcetree in such cases it works ok but cython resolves the input file to absolute path and that gets emitted into genetate _blueman.c as module name, renders the build non-reproducible, wish cython had a better way to handle this but there is not, therefore tweak the meson build rule to account for specifying workdir to cython which will search the inputs correctly, and use meson's build_root to emit the output into build dir. This ensures that it becomes independent of source or build directories and cython does not generate the absolute paths into generate C code.
See cython discussion on [1]
[1] https://github.com/cython/cython/issues/5949
=> meson: Do not emit absolute path when S != B

blueman/gui/DeviceSelectorDialog.py
The list is already populated so we can't rely on the device-selected signal to set the selected device. fixes #2500
=> DeviceSelectorDialog: Set initial selected device

CHANGELOG.md, blueman/gui/DeviceSelectorDialog.py, blueman/gui/manager/ManagerDeviceMenu.py, blueman/plugins/applet/AutoConnect.py, blueman/plugins/manager/Services.py, blueman/plugins/mechanism/Rfcomm.py, blueman/services/meta/SerialService.py, po/LINGUAS, po/eo.po, po/ga.po
=> Fixes for stable

blueman/bluez/errors.py, blueman/plugins/applet/RecentConns.py
Every 10 s, I see this error, on Ubuntu 24.04.1, which uses Blueman 2.3.5:
```
During handling of the above exception, another exception occurred:
File "/usr/lib/python3/dist-packages/blueman/main/Applet.py", line 97, in on_device_created
plugin.on_device_created(path)
File "/usr/lib/python3/dist-packages/blueman/plugins/applet/RecentConns.py", line 99, in on_device_created
self._rebuild()
File "/usr/lib/python3/dist-packages/blueman/plugins/applet/RecentConns.py", line 80, in _rebuild
self._items = self._get_items()
^^^^^^^^^^^^^^^^^
File "/usr/lib/python3/dist-packages/blueman/plugins/applet/RecentConns.py", line 199, in _get_items
return sorted(
^^^^^^^
File "/usr/lib/python3/dist-packages/blueman/plugins/applet/RecentConns.py", line 213, in <genexpr> …
```
=> Applet: Handle UnknownObject DBus error.

blueman/gui/manager/ManagerToolbar.py
**Problem**
The search button becomes unavailable after the device list is empty.
**Cause**
The _update_button() function receives None when the device list becomes empty, causing the sensitivity of the search button to be disabled if the argument (adapter) is None.
**Solution**
Pass the instance variable of ManagerDeviceList, Adapter, to the _update_button() function.
=> UI Fix: Make search button available after device list becomes empty

blueman/gui/manager/ManagerToolbar.py, data/ui/manager-main.ui, stubs/gi/repository/Gtk.pyi
This is especially noticeable when people try to use the Pair button with only keyboard as the button is skipped/not selectable when insensitive. PR is mainly to get feedback if this is what we want. One downside is that when text is slightly less readable as can be seen with the Send File button. I can also only do this for the Pair button.
This is how it looks like now:
Before:
=> Set Toolbar buttons half the opacity when not sensitive

CHANGELOG.md, blueman/bluez/errors.py, blueman/gui/manager/ManagerToolbar.py, blueman/main/Applet.py, blueman/main/DBusProxies.py, blueman/main/Manager.py, blueman/plugins/BasePlugin.py, blueman/plugins/applet/RecentConns.py, blueman/plugins/applet/StatusIcon.py, configure.ac, meson.build
Ive added #2514 and #2513 to the 2.4.4 milestone. Anything else you want to include?
I'll update this PR with the new commits and update the changelog.
=> Prepare for 2.4.4

CHANGELOG.md, blueman/main/PluginManager.py
It looks like this rarely ever manifests, but we erroneously stopped catching the exception in https://github.com/blueman-project/blueman/commit/c71294c1cc1246e55da263a9d0014c94977716df.
=> Fix fatal LoadException

blueman/bluemantyping.py, blueman/gui/CommonUi.py, blueman/gui/GenericList.py, blueman/gui/applet/PluginDialog.py, blueman/main/DbusService.py, blueman/main/PulseAudioUtils.py, blueman/main/applet/BluezAgent.py, blueman/main/indicators/GtkStatusIcon.py, blueman/main/indicators/IndicatorInterface.py, blueman/main/indicators/StatusNotifierItem.py, blueman/plugins/BasePlugin.py, blueman/plugins/ServicePlugin.py, blueman/plugins/applet/Menu.py, blueman/plugins/applet/PulseAudioProfile.py, blueman/plugins/applet/RecentConns.py, blueman/plugins/applet/TransferService.py, blueman/plugins/manager/PulseAudioProfile.py, blueman/plugins/services/Network.py, stubs/_blueman.pyi
Replace all imports from typing_extensions with standard typing, move them out of TYPE_CHECKING checks and use defined types directly instead of as strings
=> More direct types

blueman/gui/Notification.py, blueman/main/applet/BluezAgent.py, blueman/plugins/applet/ConnectionNotifier.py, blueman/plugins/applet/TransferService.py
This PR sets a timeout for connection notifications and sets the transient hint so that these notifications do not remain in the notification list.
This has been a bother for me, with my Bluetooth mouse connecting and disconnecting and piling up a list of irrelevant notifications.
=> Make connection notifications transient

.github/workflows/check.yml
Newer versions use girepository-2.0 which is not available in the python docker images.
=> CI: Pin pygobject to 3.50

blueman/gui/manager/ManagerToolbar.py, blueman/main/Manager.py
This will hide the switch if the PowerManager plugin isn't loaded.
=> Manager: Hide bt status switch when PowerManager is not available

blueman/gui/DeviceList.py, blueman/gui/GenericList.py, blueman/gui/manager/ManagerDeviceList.py
Everything that operates on or with the ListStore is prefixed with `list_` and similar for the view `view_`. Also used more understandable variables so it's more clear what is happening. For example in ManagerDeviceList the variable was `column_id` which in reality is the column number of the list and possibly be confused with the column id we have in the rowdata.
No functional changes but hopefully make it all clearer and consistent.
=> Lists: Improve naming

blueman/bluez/errors.py, blueman/plugins/applet/KillSwitch.py, blueman/plugins/mechanism/RfKill.py
Technically mechanism plugin RfKill could also not be allowed to open the device but I'm uncertain how likely this is.
Also used an enum to represent the operation and some housekeeping.
=> Use file monitor to handle changes in KillSwitch

blueman/gui/manager/ManagerMenu.py, blueman/gui/manager/ManagerToolbar.py, blueman/main/Manager.py, data/ui/manager-main.ui
This supersedes #1927. As mentioned in there, RadioMenuItems don't work with GAction in Gtk3.
The next step is to move the `Blueman`/`ManagerDeviceList` object out of `ToolBar` and `ManagerMenu` as both connect to the same `ManagerDeviceList` signals to do mostly the same thing, update the UI.
=> Use GActions where possible

blueman/main/indicators/StatusNotifierItem.py
blueman-tray restarts when a new StatusNotifierWatcher appears. This is especially relevant when blueman and a watcher like waybar get started in the session in no particular order. Unfortunately we have to use the `GLib.Error.message` and it looks like #2334 lacked the prefix; at least I cannot find any hint that this could have worked.
Fixes #2765
=> Fix handling for new StatusNotifierWatcher

blueman/Functions.py, blueman/main/Applet.py, blueman/main/DBusProxies.py, blueman/main/DbusService.py, blueman/main/Manager.py, blueman/main/Tray.py, blueman/plugins/AppletPlugin.py, blueman/plugins/applet/DBusService.py, blueman/plugins/applet/DhcpClient.py, blueman/plugins/applet/Menu.py, blueman/plugins/applet/PowerManager.py, blueman/plugins/applet/StatusIcon.py, blueman/services/meta/NetworkService.py
This moves the handling of plugin dbus services to the individual plugins. `DBusService` provides the basic services to mange the applet and it's plugins under `org.blueman.Applet`. This service should never be unloaded to avoid #2722.
Instead of tearing down `org.blueman.Applet` when a plugin is (un)loaded each plugin now provides it's own interface. Added convenience functions to the proxies to make this more manageable.
=> Appletplugin: Plugins provide dbus interfaces

blueman/plugins/services/Network.py
Otherwise the bind will trigger the toggle signal making the Apply button sensitive as if a settings changed.
=> Network service plugin: Bind nap-enable before connecting signals
